client_max_body_size 4M;

upstream filestore {
    server 127.0.0.1:8071;
}

upstream main {
    server 127.0.0.1:8080;
}

upstream nodejs {
    server 127.0.0.1:5000;
}

server {

    listen 80 default_server;

    location / {
         return 301 https://$host$request_uri;
    }     

}

server {

    listen 443 ssl default_server;
    
    #
    # SSL conf
    #
    
    ssl_certificate /etc/nginx/ssl/domain.crt;
    ssl_certificate_key /etc/nginx/ssl/domain.key;
 
    #
    # Proxy headres
    #    

    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;

    
    location ~ ^/resources/.+/(.+-app\.(js|css|js\.map)){
        proxy_pass http://nodejs/$1;
    }
    
    location /resources {
        proxy_pass http://main;
    }
    
    location /rest-api {
        proxy_set_header Host $http_host;
        proxy_pass http://main;
    }
    
    location /file-store {
        alias /var/lib/armario/filestore;
        autoindex on;
    }

    location / {
        proxy_pass http://main;
    }

    location /identity {
        proxy_pass http://main;
    }

    location /feed-hub {
        proxy_pass http://main;
    }
    
    location /catalog {
        proxy_pass http://main;
    }

    location /trade-offer {
        proxy_pass http://main;
    }
   
    location /workroom {
        proxy_pass http://main;
    }
    
    location /docman {
        proxy_pass http://main;
    }
    

}
