CREATE SEQUENCE IF NOT EXISTS script_seq START WITH 1;

CREATE TABLE IF NOT EXISTS scripts (
    id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL
    uuid UUID NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    annotation VARCHAR(2000),
    created TIMESTAMP WITH TIME ZONE NOT NULL
);
