PasswordChange=Изменение пароля
EmailForPasswordChangeCode=Email для кода изменения пароля
Email=E-mail
Ticket=Код изменения пароля
NewPassword=Новый пароль
Change=Изменить пароль
SendTicket=Выслать код
TicketSent=Код  был отправлен на вашу электронную почту.
InputTicketAndNewPass=Введите код и новый пароль
