#
# Copyright © 2018-2020 Colesico
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

WelcomeTo=Добро пожаловать в tavapava.com
NewAccountRegistration=Регистрация нового пользователя
YourName=Ваш ник (псевдоним)
Email=E-mail
Password=Пароль
SignUp=Зарегистрироваться
RegistrationAcceptedMessage=На вашу электронную почту отправлена ссылка подтверждения регистрации. \
   Для завершения регистрации пройдите по той ссылке. \n\n\
   Доставка письма может занять некоторое время. \n\
   Если вы не находите письма в вашей электронной почте проверьте (если есть) раздел 'Спам'. \n\
   Если в течении суток не последовало подтверждения, ваша регистрация аннулируется.
RegistrationConfirmedMessage=Регистрация успешно завершена! Вы можете продолжить работу с tavapava.com.
RegistrationConfirmation=Подтверждение регистрации
ConfirmationResult=Результат подтверждения
Continue=Продолжить
Registration=Регистрация
