WelcomeTo=Добро пожаловать в tavapava.com
NewAccountRegistration=Регистрация нового пользователя
YourName=Ваш ник (псевдоним)
Email=E-mail
Password=Пароль
SignUp=Зарегистрироваться
RegistrationAcceptedMessage=На вашу электронную почту отправлена ссылка подтверждения регистрации. \
   Для завершения регистрации пройдите по той ссылке. \n\n\
   Доставка письма может занять некоторое время. \n\
   Если вы не находите письма в вашей электронной почте проверьте (если есть) раздел 'Спам'. \n\
   Если в течении суток не последовало подтверждения, ваша регистрация аннулируется.
RegistrationConfirmedMessage=Регистрация успешно завершена! Вы можете продолжить работу с tavapava.com.
RegistrationConfirmation=Подтверждение регистрации
ConfirmationResult=Результат подтверждения
Continue=Продолжить
Registration=Регистрация
