NewUserRegistration=New user registration
Username=Login
Password=Password
InviteCode=Invite code
SignUp=Sign up
SignUpNotice=By clicking the "Sign Up" button, you agree to the \
 <a href="/docman/agreement" target="_blank">Terms&nbsp;of&nbsp;Service</a>
SuccessRegistration=Success registration
SuccessRegistrationNotice=Your account has been successfully registered.\
 Please <a href="/identity/login">log in</a> to continue.
