= Zacepco - Руководство по созданию сценария

© 2026 V. Larionov. Лицензия CC BY 4.0

==  Преступление, начало расследования

Классический сценарий убийства  моделируется следующим образом:

* Задается локация где произошло преступление. Эта локация является
начальной точкой расследования.
* На локацию в открытую добавляется артефакт преступления в котором
описаны некоторые связи с другими сущностями - ссылку на персонажа
которого убили, время убийства.
* Для  персонажа-трупа могут быть открыты
 какие то дополнительные артефакты, означающие что обнаружено
на трупе.
* Дополнительно для некоторых персонажей могут быть открыты
некоторые общедоступные артефакты.
* Также  другие локаци могут соержать некоторые открытые артефакты.

Детективам выдается ресурс на расследование.

Детективы, исходя из начально открытых артефактов продолжают
расследование, путем построения дедуктивных гипотез, обыска локаций,
допроса персонажей и выполнения экспертиз.

Ход расследования предполагает, что улики должны находиться
последовательно, т.е. одни найденные улики должны указывать на другие и
так пока не приведут к преступнику. Логичным первым шагом является обыск
места преступления.

== Рекомендации по размещению улик

Для обыска локации - ограничивать количество улик в  локациях, добалвять ложные.
Ключевые улики и связи должны быть доступны только через допрос или экспертизу

== Шаблон сценария
<<script-template.adoc, См. шаблон>>

== Практические приемы для сценариев.

Связь локаций по перемещению артефактов из одной локации в другую. В
одной локации найден предмет, изначально находящийся в другой.

Связь персонажа с локацией через связь артефактов. Например окурок
сигареты в локации и пачка сигарет у персонажа:

* Артефакт в локации L1 - A1: Окурок сигареты марки ++[++Camel++]++
* Артефакт у персонажа P1 - A2: Пачка сигарет марки ++[++Camel++]++



Сценарий также может определять в какой локации артефакт был изначально
до преступления и потом пропал из нее. Такой факт описывается в виде
другого артефакта. Например Артефакт # 66: “В этой локации отсутствует
артефакт A++[__]++. Хотя ранее он в ней находился”.

Привязка артефактов к последовательности тактов.

Связь через процесс? Например молотком забивать гвозди?

Сигарета - пачка : часть-целое

Условные улики - указывает на что то при условии что есть определенная
другая улика. Например в такой-то локации найдена сигарета такой-то
марки. И второй артефакт - такой то персонаж курит сигареты такой-то
марки.

Расследование всегда начинается с локации места преступления, например
локации, где обнаружен труп.

Не все артефакты в игре могут иметь отношение к преступлению, часть из
них для расследования бесполезна. Для сценариев с легкой сложностью все
клики имеют отношение к преступлению (из игры исключаются бесполезные
артефакты)

Некоторые возможные стратегии поиска клик:

* Детектив знает что искать но не знает где
* Детектив не знает что искать но знает где
* Неуместные артефакты - предмет которого не должно быть в данной
локации

=== Взаимодействие персонажей

Если персонажи находятся одновременно в локации, персонаж может что то
сказать другому персонажу, например, что он собирается делать, или
передать предмет.

Персонаж если находился в одной локации с другим персонажем дает об этом
показания. Если в соседней - дает показания что кого-то видел в такой то
клетке, без конкретизации кого именно.

Камеры установленные в локации дают полный лог того что происходило в
локации.

Персонаж может находиться в локации какое-то время и находясь в локации
персонаж может что-то в ней делать. Для каждого вида локации и роли
персонажа определен список действий персонажа в локации?

Нужно ли вводить сущность действия персонажа?

Например - кто угодно может плавать в бассейне. На кухне повар может
готовить.

Если инспектор спрашивает что вы там делали персонаж отвечает.