= Zacepco - Механика детективной игры

© 2026 V. Larionov. Лицензия CC BY 4.0

== О документе

Документ описывает механику детективной игры, задает общие правила по которым  она должна строится.
Для целостности игры неотъемлемым дополнением к этой механике являются *сценарии преступления*, которые описывают
сюжетную составляющую. Сама механика по сути является *фреймворком* дедуктивной детективной
игры с элементами случайности.

== Сценарий преступления

Сценарий, в рамках механики, описывает преступление, которое уже произошло. В процессе игры игроки (детективы)
должны раскрыть это преступление. Сценарий ориентируется на разную степень сложности раскрытия преступления,
описывая, например,  одно преступление или сразу несколько, с участием одного или нескольких преступников,
с наличием или отсутствием сообщников, с разным количество действующих лиц, длительностю преступления,
размером “театра действия” т.п.

Любой сценарий содержит:

* Инструкции для подготовки к началу расследования.
* Информацию для хода расследования.
* Раздел “Ответы”, который можно посмотреть в конце игры.

Готовые сценарии идут с игрой, либо же генерируются специальной
программой.

Игра происходит по выбраному игроками сценарию и делится на две *фазы*.

В первой фазе игроки, согласно сценария, выполняют подготовительные
действия для начала расследования - сборка игрового поля и др.

Вторая фаза - расследование, кооперативный процесс раскрытия
преступления детективами.

В конце игры выводы следствия сравниваются с разделом “Ответы” сценария.

== Игровые сущности и связи

Сценарий оперирует следующими типами *игровых сущностей*:

* *Персонаж (P)* - действующее лицо в преступлении;
* *Локация (L)* - часть места действия преступления;
* *Артефакт (A)* - часть информации о преступлении;
* *Время (T)* - момент времени в течении преступления;

Сами игровые сущности (кроме времени) представлены карточками сущностей.
Каждая такая карточка, в зависимости от типа сущности имеет свой формат.
Сущность идентифицируется уникальным номером (идентификатором), например P2 или L5.
Время - не имеет собственных карт, порядковый только номер  (T1,T2 ...).

Каждая из игровых сущностей может быть связана сценарием с любыми
другими сущностями. С точки зрения связи, когда одна сущность ссылается
на другую, первая называется *ключевой сущностью*, а вторая - *целевой
сущностью*.

Сценарий задает совокупность игровых сущностей и их связей, что по сути
описывает преступление. (Определяет модель преступления).

Часть из этих сущностей и связей могут не относится к преступлению и
служат для усложнения процесса расследования.

Перед началом расследования детективам известна некоторая небольшая
часть сущностей и их связей. В процессе расследования детективы
постепенно открывают остальные карты сущностей и связи.

== Открытие сущностей и связей

В игре используется механика *поэтапного* открытия детективами карт
сущностей и обнаружения связей между ними.

Детективы на основе некоторых уже открытых ключевых сущностей могут узнать
их связи с другими целевыми сущностями, как открытыми, так еще и не
открытыми. Потом отобрать другие ключевые сущности и по ним опять
определить очередные целевые сущности и связи, и так далее.

Связи сущностей, в зависимости от конкретной игровой механики
описываются сценарием в виде** таблиц связей **определенного формата.

При получении информации из таблиц связей, чтобы не раскрыть перед
детективами сразу всю информацию о преступлении, используется
*компьютерная программа*. Либо же ее роль берет на себя один из игроков
(*мастер*), только он может видеть эти таблицы. Так как такой игрок
обладает доступом сразу ко всей информации о преступлении, он _не может_
исполнять роль детектива.

== Элемент случайности

Кубик D12

== Ресурс, бонус

В игре каждое действие детектива стоит определенного *ресурса*. В случае
успешности действия игроку начисляются *бонус*. Сценарий определяет общий
*бюджет* ресурса на расследование. При исчерпании бюджета расследование
завершается _неудачно_.

Индивидуальное кол-во бонуса определяет лучшего детектива в
расследовании.

== Игровое время

Сценарий преступления охватывает какой-то промежуток времени. Время в
этом промежутке течет дискретно, *тактами*, с первого до последнего.
Преступление длится заданное в сценарии число тактов. Чем больше тактов,
тем сложнее раскрыть преступление. Все события в преступлении
привязываются к тактам. В каждый такт времени происходит
то-то. Считается что между тактами ничего не происходит.

== Игровое поле, локации, проходы

В сценарии игровое поле определяется в виде графа. В фазе подготовки к
расследованию игроки на основе этого графа из отдельных *локаций* (узлы
графа) собирают игровое поле.

Локация представляет собой квадратную карту. Каждая из локаций имеет
уникальный идентификатор и вид, например: Парковка, Коттедж, Сарай, Бассейн,
Заброшенный дом, Коллектор, Погреб, Беседка, Лес, Лаунж-бар,
Болото,Парковка, Гараж, Пруд, Лодочный домик, Руины, Пещера, Кладбище,
Старый крематорий, Лесопилка, Водопад, Домик лесника, Гостевой дом,
Часовня, Колодец, Оранжерея, Склеп, Конюшня, Овраг, Поляна, Пасика и
т.п.

Локации соединяются между собой *проходами* для персонажа.
Проход может состоять из нескольких карт прохода (сегментов) с разной
конфигурацией прохода (прямой, поворот). Проход всегда соединяет только
две локации. В проходах никогда ничего не происходит, они лишь служат
для указания возможности перемещения персонажей между локациями.

Сценарий также может предполагать наличие *“скрытых” проходов* между
локациями, которые не обозначаются в фазе подготовки к расследованию. О
существовании таких проходов детективы узнают в процессе расследования.
При открытии в какой-то локации *артефакта скрытого прохода* определяется
номер смежной целевой локации в которую ведет проход. На поле выкладывается
карта прохода соединяя
локацию в которой был открыт артефакт скрытого прохода и целевой
локацией.

Скрытый проход может вести в *скрытую локацию*. Это такая локация, о
которой детективы не знают до начала расследования. В качестве скрытой
локации может выступать любая из локаций, еще не включенная в игровое
поле. Обнаруженная скрытая локация выкладывается на игровое поле рядом с
той локацией где был обнаружен артефакт скрытого прохода. Локация
соединяется картой прохода с той локацией где был обнаружен артефакт
скрытого прохода. После открытия локации она становится доступной для следсвтвенных
действий.

Информация о всех скрытых проходах и локациях явно указывается в разделе
*ответы* сценария.

При разработке сценария должен учитываться смысл локации. Например в
пещере может не быть света, в подвал персонаж может войти только с
ключем, в оранжерее может расти ядовитое растение, бар работает с 3-го
до 6-го такта и др. Смысловая нагрузка локации должна опмогать детективам в расследовании.

== Персонажи

Действующее лицо в преступлении - это *игровой персонаж*. Набор
персонажей в игре определяется сценарием. Сценарий задает явных
персонажей, они известны перед началом расследования. Их карты
выкладываются рядом с игровым полем.

Сценарий может также подразумевать, наличие *скрытых персонажей*. Скрытый
персонаж - один из тех, чья карта еще не выложена из колоды персонажей в
открытую на стол. Определить наличие скрытого персонажа можно в процессе
расследования, логически, на основе обнаруженных артефактов. Либо же,
при открытии артефакта  с прямой ссылкой на этого скрытого
персонажа. При обнаружении артефакта с сылкой на скрытого персонажа его карта из
колоды персонажей выкладывается в открытую рядом с игровым полем к
картам остальных персонажей. После этого персонаж становится доступным для следственных действий.
В сценарии, в разделе “Ответы”, перечислены все
скрытые персонажи.

Персонажи представлены карточками. Каждому персонажу соответствует свой
цвет и имя, в качестве номера (идентификатора) - уникальная буква,
первая буква имени.


== Движения и действия персонажа

У каждого персонажа во время преступления в каждый такт времени есть
только следующие *альтернативные* возможности:

* Перейти в соседнюю локацию и ничего не делать.
* Перейти в соседнюю локацию и выполнить какое либо действие.
* Остаться в локации и выполнить какое либо действие.

Перемещение происходит в смежную локацию при наличие  прохода.
Со стороны сценария также возможны какие-либо  ограничения на проход, например
дверь, которую нужно открыть ключем.
В общем случае персонаж может посещать одну и ту же локацию несколько раз в разных
тактах. Для более легких вариантов игры - персонаж может посетить
локацию только один раз.

Путь движения персонажа (последовательность локаций) подразумевается
сценарием, но игрокам явно не раскрывается. Игроки должны определить
этот путь при расследовании.

Пути персонажей раскрываются сценарием в разделе “Ответы” - для каждого
персонажа обозначены его перемещения в виде последовательности номеров
локаций для каждого такта. Эту информацию можно посмотреть в конце игры.

Во время фазы расследования, для визуализации пути (*трека*) движения
персонажа по игровому полю в локации выкладываются жетоны цвета
персонажа. На каждом жетоне номер такта в котором персонаж находился в
локации на которой лежит жетон. Такие жетоны называются жетоны трека
персонажа.


При нахождении в локации персонаж может выполнить какое либо одно действие.
Само действие как сущность механика не предусматривает, но результатом этого действия
становится  *артефакт*, который остается либо в локаци, либо у персонажа который совершил
дейсвтвие либо над которым совершено действие.

== Артефакты

*Артефакт* - часть сведений о совершенном преступлении, которую
последовательно обнаруживают игроки при расследовании. Артефакт представлен
карточкой артефакта, на которой описывается какой
либо физический предмет, событие, какая-то информация, факт. Также может
присутствовать руководство к действию игрока в связи с этим артефактом.

Примеры артефактов: свидетельское показание, мотив, записка, окурок
сигареты, привычка, пристрастие персонажа к курению, факт отсутствия предмета в
локации.

Каждый артефакт в игре имеет уникальный номер (идентификатор) например A1, A88 и т.п. На
рубашке карточки артефакта - номер артефакта, на обратной стороне -
описание, изображение, признак наличия *“параметров”*   (параметры см. ниже).

Сценарий преступления определяет набор артефактов, участвующих в игре
через таблицы связей.

Некоторые из артефактов могут не иметь отношения к преступлению и служат
для того чтобы усложнить игру. Чем больше таких артефактов тем сложнее
игра.

Изначально артефакты скрыты от детективов. В процессе расследования
детективы постепенно “открывают” артефакты - выкладывают в открытую карты
артефактов из колоды.

Если в открытом артефакте есть ссылки на другие артефакты, эти артефакты
также открываются (рекурсивно). Сценарий не должен определять глубокую
рекурсию открываемых артефактов.

== Параметры артефактов

При открытии карты артефактов, если на его карте стоит пиктограмма
“параметры” , то по таблице связей сценария *“Параметры артефактов”* по
номеру уточняемого артефакта находятся значения параметров, которая
записывается стираемым маркером на карту артефакта.

Параметрами артефакта могут быть: такты, номера локаций, персонажей,
других артефактов. 

Помимо этого в качестве артефактов могут указываться
уникальные произвольные текстовые наименования - *виртуальные
артефакты*. Этот механизм используется если в сценарии требуется
сослаться на какой то артефакт, карточки которого нет в игре. В этом
случае используется просто уникальное название виртуального артефакта.

В таблице некоторые параметры могут не иметь значений. Это означает что
они точно не известны.

Формат таблицы свзей “Параметры артефактов”

|===
|Артефакт |Параметры

|A1|P2, T8, L5
|A2 |L16
|A6 |A=С2 (сценарный артефакт)
|A12 |T4
|A13 |P?, T3, A=Кувалда  (виртуальный артефакт)
|===

Примеры:

* Артефакт #1 : “Показания. Видел персонажа [P] во время [T] таков в локации [L]”
* Артефакт #2 : “В этой локации обнаружен скрытый проход в локацию
[L]. Соедините проходом нужные локации. Если проход ведет в
скрытую локацию - выложите эту локацию на поле”
* Артефакт #6 : “В этой локации отсутствует артефакт [A] который
изначально находился тут”
* Артефакт #12 : “Сломанные часы. Стрелка показывает [T] тактов”
* Артефакт #13 : “В этой локации был замечен персонаж [P] в [T] тактов с [A] в руке”.


== Кастомные артефакты

Сценарием, помимо общих для разных сценариев артефактов, поставляемых с игрой,
также могут быть предусмотрены
*кастомные артефакты* - их текст полностью записан в сценарии в виде готовх для печати
карточек, которые можно распечатать перед игрой. Либо альтернативно -
при открытии кастомного артефакта записать его текст смываемым маркером на
специальную пустую карточку сценарного артефакта (или простую бумажку).

Доступ к кастомным артефактам сценария есть только у мастер игрока
или программы. Каждый сценарный артефакт имеет уникальный *в пределах сценария* номер с
префиксом “С”.

Для уменьшения вероятности читерства необходимо чтобы распределение
важности для расследования кастомных артефактов было такое же как и у
общих, включая процент ложных. Иначе игроки будут или игнорировать
их или наоборот стремится использовать в установлении связей.


== Обыск локации

При проведении расследования детективы могут *“обыскать”* любую открытую локацию (в
том числе и ранее скрытую) чтобы попытаться открыть артефакты, связанные
с этой локацией. В результате обыска с некоторой вероятностью может быть
"обнаружен" (открыт) артефакт.

В сценарии есть таблица связей *“Обыск локаций”* которая задает связь
между локациями и артефактами. При обыске используется механика
вероятностного обнаружения артефакта вместе с механикой *“Фокус обыска”*,
которая позволяет с большей вероятностью обнаружить артефакт на который
направлен фокус обыска и получить больше бонуса.
Кроме этого, за доплату обыск может быть  *"Детальным"*.
Обычный обыск  не дает гарантии обнаружения артефакта, в то время как
детальный - более дорогой, всегда обнаруживает какой либо из неоткрытых артефакт.

Попытка обыска стоит ресурса. Для каждой локации своя стоимость. За
успешный обыск детективу начисляются бонусы пропорционально кол-ву
использованных детективом сущностей в фокусе обыска.

Детектив заявляют о проведении обыска в конкретной локации. Объявляет
ключевые сущности в фокусе обыска - их номера. Опционально может
объявить обыск *“детальным”*, доплатив ресурс.
Кидает дайс D12 и по таблице “Обыск локаций” определяют какой артефакт
следует открыть.

Таблица “Обыск локаций” имеет следующий формат:

|===
|Локация|Стоимость|Доплата 4+|Фокус обыска|Сдвиг|Порог |Артефакт|Бонус

|       |         |          |Персонаж |Локация |Артефакт |Время ||||
|L1 |3|2|P4 |L3,L4 | - |T4  |2  |10 |A8 | 1
| * |  * | * | -|-|A5 | - |4 |7|A3 | 3
|L5 |4|2| -  |   -   |-  |   - | 3 |8  |A12 | 2
|===

*Локация* - номер обыскиваемой локации.

*Стоимость* - стоимость обычного обыска. Сколько ресурсов тратится
на попытку обыска в локации. Стоимость озвучивается детективу до попытки
обыска. После того как детектив узнает стоимость, он может отказаться от обыска,
при этом ресурс не тратится.

*Доплата* - доплата к стоимости обыска за детальность. Обеспечивает “страховку” от неоткрытия
артефакта при неудачном броске кубика (см. “Порог”)

*Порог* -  порог обнаружения артефакта. Число, которое сравнивается с выпавшим на дайсе.
Если выпало больше или равное числу в этой колонке (с учетом снижения
порога, см. ниже), считается что артефакт обнаружен. Строки в таблице
упорядочены по убыванию порога обнаружения для локации. Сравнение значений идет
последовательно сверху вниз, до первого успешного обнаружения. Если
какие-то артефакты уже были обнаружены ранее, соответствующие строки
пропускаются.

Если подходящей строки не найдено:

* В случае детального обыска (с доплатой) - в локации открывается  артефакт с самым низким порогом.
  Считается что при детальном обыске детектив нашел что-то подозрительное.
* В случае обычного обыска  - объявляется что ничего не найдено.

В сценарии порог обнаружения прописывается таким образом, чтобы наиболее
важные для следствия артефакты имели наименьшую вероятность обнаружения
(большие значения порогов).

*Фокус обыска* - служит для повышения вероятности открытия важного артефакта.
Для одного и того же артефакта порог обнаружения с фокусом  всегда ниже чем
без фокуса ( см. “<<lowthreshold,Снижение порога>>” ), т.к. считается что при наличие
фокуса обыск будет более целенаправленным.

Если детектив обозначил фокус обыска - указал номера открытых ключевых сущностей,
то определение артефакта идет среди строк, соответствующих фокусу
обыска.Если такого соответствия не выявлено, поиск идет по всем
строкам без учета фокуса обыска.

При открытии артефакта для поиска которого был обозначен фокус
обыска но соответствие с фокусом не найдено считается что детектив не
нашел что искал, но нашел что-то подозрительное (несоответствие фокусу
обыска понятно детективу из самого обнаруженного артефакта).

Соответствие фокуса обыска определяется по тому же самому алгоритму
что и при допросе персонажа для определения целевого артефакта
(см. "<<targetartalg,Алгоритм определения целевого артефакта>>")

В ячейке фокуса можно через запятую перечислить несколько номеров сущностей - это
трактуется как любая из них.

Фокус обыска детектива может состоять из любых *открытых* сущностей.
Для фокуса обыска детктив может указать *максимум по одной* сущности каждого типа.

[[lowthreshold]]
*Сдвиг* - величина снижения порога обнаружения. Порог обнаружения снижается на указанную величину
для каждой  ключевой сущности в фокусе обыска  детектива. Например если в фокусе
обыска детектива  N сущностей и величина снижения указана M то итоговый порог перед сравнением
нужно уменьшить на N * M

*Артефакт* - номер открываемого артефакта.

Карта обнаруженного артефакта достается из колоды и выкладывается в
открытую на локацию или рядом. Либо же отдельно, но на локацию кладется
жетон артефакта с номером артефакта (чтобы было видно что артефакт
обнаружен в этой локации)

Если все артефакты локации открыты, на локацию выкладывается жетон
“Обыск невозможен”.

*Бонус* - бонусная ставка для начисления бонусов детективу при успешном обыске.
Начисляемое количество бонуса расчитывается по следующиму правилу:

. Одна ставка за успешность обыска.
. Если соответствует фокус внмания - дополнтельно начисляется:  ставка * количество сущностей в фокусе обыска детектива.


[[interrogation]]
== Допрос персонажа

Сценарий с каждым из персонажей связывает некоторые артефакты.
Считается, что часть из этих артефактов была у персонажей до
преступления, например - одежда, личные вещи. Часть они получили во время
преступления - подобрали в локациях или получили от других персонажей,
например кувалда, записка. Часть артефактов персонажа описывают их
неотъемлемые черты, например привычки, пристрастие к алкоголю, характер
и т.п. Остальная часть артефактов - свидетельские показания персонажей.
Сценарий также предполагает, что в процессе преступления персонажи могут
оставлять артефакты в локациях, передавать/подкидывать другим персонажам
при встрече с ними в одной локации.

Часть артефактов персонажа может быть известна игрокам (например одежда
и т.п.). Другая часть артефактов персонажа изначально неизвестна
игрокам. Аналогично процедуре обыска локации, для открытия таких
артефактов, связанных с персонажем детектив может *“допросить”* любого открытого
персонажа (в том числе и ранее скрытого). В результате допроса может
быть открыт очередной артефакт персонажа. Детектив “спрашивает”
персонажа об одной или нескольких известных детективу ключевых
сущностях - т.е. определяет *фокус допроса*. Если персонажу “известно” о
них, открывается связанный с этими сущностями артефакт, который у него есть.
По сути допрос персонажа - проверка гипотез детективов о связи сущностей,
а также возможность выявления новых связанных сущностей.

При ответе персонаж может “сказать неправду” - открывается артефакт
который на самом деле никак не связан с ключевыми сущностями. Сценарий
регулируют кол-во “ложных” артефактов

Допрос персонажа стоит ресурса. Для каждого персонажа указывается своя
стоимость. Если игроку при допросе удалось открыть артефакт ему
начисляется бонус пропорционально количеству сущностей в фокусе допроса детектива.

Для допроса персонажа используется таблица связей “Допрос персонажа”:

|===
|Персонаж |Стоимость  4+|Фокус допроса  |Артефакт |Бонус

|||Персонаж |Локация |Артефакт |Время | |
|P1 |3  |P2 |L3 |A4,A5 |T2 |A3|2
|P4 |3|-|-|A4 |T5,T6 |A12 |3
| * | * |P5|-|- |- |A15 |1
|===

*Персонаж* - допрашиваемый персонаж. Детектив на основе известных ему из хода
расследования данных и логических заключений выбирает персонажа которого
нужно допросить.

*Артефакт*  -  целевой артефакт персонажа, который открывается при успешном допросе.

*Стоимость* -  стоимость допроса персонажа. Сколько тратится ресурса за попытку
допроса персонажа. Стоимость озвучивается детективу до попытки допроса. После того как
детектив узнает стоимость, он может отказаться от допроса, при этом ресурс не тратится.

*Бонус* - бонусная ставка для начисления  бонусов детективу при успешном допросе.
Общее количество бонуса вычисляется по правилу: ставка ++*++ кличество сущностей в фокусе
допроса детектива.

*Фокус допроса* - ключевые сущности связанные с артефактом. Детектив на основе
известных из хода расследования данных и логических заключений выбирает
некоторые из *открытых*  сущностей. Для номера нужного персонажа в
таблице в колонках фокуса допроса
ищется набор ключевых сущностей  который в наибольшей степени соответствует набору номеров
выбранных детективом сущностей.

Если такой набор найден - открывается соответствующий ему артефакт. Этот артефакт может
быть задан сценарием преднамеренно не верно - имитация того, что персонаж лжет/забыл.

В ячейках фокуса допроса  можно через запятую перечислить несколько номеров -
трактуется как любой из них.

Детектив при выборе ключевых сущностей для фокуса допроса может задавать только по одной
сущности каждого типа.  При этом оне может использовать только *открытые* сущности.

В  фокусе допроса в таблице указываются только те сущности которые
упоминаются в самом целевом артефакте.

Механика построена таким образом, чтобы детективу, без знания ключевых
артефактов было бы затруднительно открыть какой либо целевой артефакт персонажа.

[[targetartalg]]
=== Алгоритм определения целевого артефакта

Алгоритм определения целевого артефакта преследует следующую цель:
задавая более конкретный вопрос (с большим количеством сущностей в фокусе допроса)
детектив заработает больше бонуса. Если вопрос детектива
более “общий” ( детектив использует меньшее количество ключевых
сущностей в фокусе допроса) он все равно получит целевой артефакт но заработает меньше
боуса. В таблице “Допрос персонажа ” артефакты для локации упорядочены
по важности для раскрытия преступления (самые важные внизу - неважные
вверху)

. В таблице “Допрос персонажа” в колонках фокус допроса, ищется полное совпадение
сущностей с сущностями выбранными детективом для фокуса допроса. Если найдено - открывается
артефакт. Если не найдено определяется лучшее соответствие.
. При определении лучшего соответствия отбираются все строки которые
содержат все сущности выбранные детективом. Если таких строк нет - опрос
неуспешен. Среди отобранных строк выбирается строка с наименьшим кол-вом
сущностей (т.е. где меньше всего “лишних” сущностей). Если таких строк
несколько - выбирается первая с наименьшей важностью из еще не открытых
артефактов. Открывается артефакт соответствующий выбранной строке.

== Экспертиза улик

В случае необходимости подтверждения гипотезы детективы могут обратится
к экспертам для проверки существования связи между открытми
сущностями. Например определить, соответствует ли пепел найденный в
локации сигаретам найденным у персонажа.

Цель экспертизы - выявить наличие связи между открыми сущностями у которых
нет прямых отсылок друг на друга. В процессе экспертизы с некоторой вероятностью
может быть выявлнны также и дополнительные связи с другими сущностями. Для увеличения вероятности
выявления *"дополнительных связей"* детектив может  предоставить *"вспомогательные улики"*.

Проведение экспертизы стоит определенного ресурса. Величина ресурса для
любой экспертизы постоянна, указывается в сценарии. За успешно найденную связь детективу
начисляется бонус.

Экспертиза по одной паре сущностей может быть произведена несколько раз с целью попыток
выявления дополнительных связей. Повторные экспертизы также имеют стоимость, но отличную от
первоначальной (дешевле). Эта стоимость указывается в сценарии.

Для проведения экспертизы (для анализа) детектив выбирает две *открытых* сущности.
Опционально предоставляет *"вспомогательные улики"* - некоторые из других открытых сущностей,
которые по мнению детектива могут быть связаны с двумя анализируемыми сущностями.
Бросает дайс D12 и по таблице “Экспертиза сущностей” определяется
выявлена ли связь или нет, наличие дополнительных связей.

Эта таблица доступна только мастеру или через
программу.

По завершению экспертизы заполняется карточка “Экспертное заключение”
где указывается номера исследуемых сущностей, результат экспертизы
(установлена связь или нет, допполнительные связи)

Пример таблицы “Экспертиза улик”:

|===
2+|Улики 4+|Вспомогательные улики           |Сдвиг | Порог |Связи|Бонус
|   |      |Персонаж |Локация|Артефакт|Время|      |       |     |

|A2 |A4    |    -    |  L3,L5|   -    |  T4 |    2 |8      |A6   |3
|P4 |L3    |     P2  |   -   |   -    |   - |   4  |10     |A3,L1|4
|===

*Улики* - номера сущностей между которыми
проверяется наличие связи. Для экспертизы детективом всегда должны быть заявлены две
*открытые* сущности. Если в таблице нет совпадений с номерами выбранных
детективом сущностей, объявляется - связь не выявлена. Если есть - обьяввляется что связь
выявлена и проверяется “Порог” для возможного открытия дополнительных связей с
другими сущностями.

*Вспомогательные улики* - номера открытых сущностей для помощи экспертизе в выявлении
дополнительных связей. Могут опционально указываться детективом до начала экспертизы.
При их совпадении с табличными уменьшается "Порог" выявления дополнительных связей на величину
“Сдвиг” для каждой совпавшей вспомогательной сущности, либо увеличивается для каждой несовпавшей.
Это моделирует наличие дополнительной информации, что в случае ее полезности делает экспертизу более
"качественной" и наоборот. Детектив может указать не более одной вспомогательной сущности каждого типа.
В таблице в одной ячейке может быть перечислено несколько номеров - это при сопоставлении
трактуется как один из них.

Алгоритм сопоставления вспомогательных сущностей см. нижке.

*Сдвиг* - величина изменения  порога выявления  дополнительных связей для каждой
вспомогательной сущности.

*Порог* -  порог выявления  *дополнительных* связей.
Число, которое сравнивается с выпавшим на D12, если
на дайсе больше (с учетом "сдвига"), то открываются сущности из колонки "Связи".

*Связи* - дополнительные связи с другими сущностями. В случае успешного броска D12
в сравнении с порогом (с учетом "дельты") открываются указанные в этой
колонке сущности.

*Бонус* - бонусная ставка для начисления бонусов детективу при успешной экпертизе.
Начисляемое количество бонуса расчитывается по следующиму правилу:

. Одна ставка за успешность экспертизы  (установление связи).
. Дополнительно по одной ставке за каждую открытую дополнительную связь.

== Алгоритм сопоставления вспомогательных сущностей при экспертизе

Детектив для экспертизы предоставляет не более одной открытой сущности в качестве вспомогательных.

Сравниваются все вспомогательные сущности предоставленные детективом для экспертизы с табличными для
конкретной пары сущностей между которыи проверяется наличие связи.

Если вспомогательная сущность оказалась "полезной"  для экспертизы (совпала с табличной),
то порог уменьшается на значение сдвига.

Если вспомогательная сущность предоставленная детективом  оказалась бесполезной (отсутствует в таблице),
считается что эта информация вредит экспертизе и поэтому к порогу прибавляется значение сдвига.

== Прямые связи сущностей

Прямая связь между любыми сущностями возможна через упоминание в артефакта а также
в таблице Экспертиза сущностей. Также связи затаюся согласно таблице:
|===
| |Локация |Время |Артефакт |Персонаж

|Локация |Переходы между локациями| |Обнаружение артефакта в локации|
|Время | |Соседние такты||
|Артефакт | | || Обнаружение артефакта у персонажа
|Персонаж | | | |
|===

== Шаблон сценария
<<script-template-ru.adoc, См. файл script-template.adoc>>

== Руководство по созданию сценария
<<script-guide-ru.adoc, См. файл script-guide-ru.adoc>>