= Zacepco - Механика детективной игры

© 2026 V. Larionov. Лицензия CC BY 4.0

== О документе

Документ описывает механику детективной игры, задает общие правила по которым  она должна строится.
Для целостности игры неотъемлемым дополнением к этой механике являются *сценарии преступления*, которые описывают
сюжетную составляющую. Сама механика по сути является *фреймворком* дедуктивной детективной
игры с элементами случайности.

== Сценарий преступления

Сценарий, в рамках механики, описывает преступление, которое уже произошло. В процессе игры игроки (детективы)
должны раскрыть это преступление. Сценарий ориентируется на разную степень сложности раскрытия преступления,
описывая, например,  одно преступление или сразу несколько, с участием одного или нескольких преступников,
с наличием или отсутствием сообщников, с разным количеством подозеваемых, длительностю преступления,
размером “театра действия” т.п.

Любой сценарий содержит:

* Инструкции для подготовки к началу расследования.
* Информацию для хода расследования.
* Раздел “Ответы”, который можно посмотреть в конце игры.

Готовые сценарии идут с игрой, либо же генерируются специальной
программой.

Игра происходит по выбраному игроками сценарию и делится на две *фазы*.

В первой фазе игроки, согласно сценария, выполняют подготовительные
действия для начала расследования - сборка игрового поля и др.

Вторая фаза - расследование, кооперативный процесс раскрытия
преступления детективами.

В конце игры выводы следствия сравниваются с разделом “Ответы” сценария.

== Игровые сущности и связи

Сценарий оперирует следующими типами *игровых сущностей*:

* *Персонаж (P)* - действующее лицо в преступлении;
* *Локация (L)* - часть места преступления;
* *Улика (X)* - часть информации о преступлении;
* *Время (T)* - момент времени в течении преступления;

Сами игровые сущности (кроме времени) представлены карточками сущностей.
Каждая такая карточка, в зависимости от типа сущности имеет свой формат.
Сущность идентифицируется уникальным номером (идентификатором), например P2, L5, X55.
Время - не имеет собственных карт, порядковый только номер  (T1,T2 ...).

Каждая из игровых сущностей может быть связана сценарием с любыми
другими сущностями. С точки зрения связи, когда одна сущность ссылается
на другую, первая называется *ключевой сущностью*, а вторая - *целевой
сущностью*.

Сценарий задает совокупность игровых сущностей и их связей, что по сути
описывает преступление. (Определяет модель преступления).

Часть из этих сущностей и связей могут не относится к преступлению и
служат для усложнения процесса расследования.

Перед началом расследования детективам известна некоторая небольшая
часть сущностей и их связей. В процессе расследования детективы
постепенно открывают остальные карты сущностей и связи.

== Открытие сущностей и связей

В игре используется механика *поэтапного* открытия детективами карт
сущностей и обнаружения связей между ними.

Детективы на основе некоторых уже открытых ключевых сущностей могут узнать
их связи с другими целевыми сущностями, как открытыми, так еще и не
открытыми. Потом отобрать другие ключевые сущности и по ним опять
определить очередные целевые сущности и связи, и так далее.

Связи сущностей, в зависимости от конкретной игровой механики
описываются сценарием в виде *таблиц связей* определенного формата.

При получении информации из таблиц связей, чтобы не раскрыть перед
детективами сразу всю информацию о преступлении, используется
компьютерная программа - *мастер-программа*.

== Элемент случайности

Дайс D12

== Ресурс, очки

В игре каждое действие детектива стоит определенного *ресурса*. В случае
успешности действия игроку начисляются *очки*. Сценарий определяет общий
*бюджет* ресурса на расследование. При исчерпании бюджета расследование
завершается _неудачно_.

Индивидуальное кол-во заработанных очков определяет лучшего детектива в
расследовании.

== Игровое время

Сценарий преступления охватывает какой-то промежуток времени. Время в
этом промежутке течет дискретно, *тактами*, с первого до последнего.
Преступление длится заданное в сценарии число тактов. Чем больше тактов,
тем сложнее раскрыть преступление. Все события в преступлении
привязываются к тактам. В каждый такт времени происходит
то-то. Считается что между тактами ничего не происходит.

== Место преступления, локации, проходы

В сценарии место преступления определяется в виде графа. В фазе подготовки к
расследованию игроки на основе этого графа из отдельных *локаций* (узлы
графа) собирают место преступления.

Локация представлена квадратной картой с изображением локации. Также на карте
отмечается ID локации, название. Сценарий в дополнение клокации предоставляет описание
локации, где значится ключевая с точки зения сценария информация о локации.

Примеры локаций: Парковка, Коттедж, Сарай, Бассейн,
Заброшенный дом, Коллектор, Погреб, Беседка, Лес, Лаунж-бар,
Болото,Парковка, Гараж, Пруд, Лодочный домик, Руины, Пещера, Кладбище,
Старый крематорий, Лесопилка, Водопад, Домик лесника, Гостевой дом,
Часовня, Колодец, Оранжерея, Склеп, Конюшня, Овраг, Поляна, Пасика и
т.п.

Локации соединяются между собой *проходами* для персонажа.
Проход может состоять из нескольких карт прохода (сегментов) с разной
конфигурацией прохода (прямой, поворот). Проход всегда соединяет только
две локации. В проходах никогда ничего не происходит, они лишь служат
для указания возможности перемещения персонажей между локациями.

Сценарий также может предполагать наличие *“скрытых” проходов* между
локациями, которые не обозначаются в фазе подготовки к расследованию. О
существовании таких проходов детективы узнают в процессе расследования.
При открытии в какой-то локации *улики скрытого прохода* определяется
номер смежной целевой локации в которую ведет проход. На поле выкладывается
карта прохода соединяя локацию в которой была открыта улика скрытого прохода и целевой
локацией.

Скрытый проход может вести в *скрытую локацию*. Это такая локация, о
которой детективы не знают до начала расследования. В качестве скрытой
локации может выступать любая из локаций, еще не включенная в игровое
поле. Обнаруженная скрытая локация выкладывается на игровое поле рядом с
той локацией где была обнаружена улика скрытого прохода. Локация
соединяется картой прохода с той локацией где была обнаружена улика
скрытого прохода. После открытия локации она становится доступной для следсвтвенных
действий.

Информация о всех скрытых проходах и локациях явно указывается в разделе
*ответы* сценария.

При разработке сценария должен учитываться смысл локации. Например в
пещере может не быть света, в подвал персонаж может войти только с
ключем, в оранжерее может расти ядовитое растение, бар работает с 3-го
до 6-го такта и др. Смысловая нагрузка локации должна опмогать детективам в расследовании.

== Персонажи

Действующее лицо в преступлении - это *персонаж*. Набор
персонажей в игре определяется сценарием. Сценарий задает явных
персонажей - они известны перед началом расследования. Их карты
выкладываются рядом с игровым полем.

Сценарий может также подразумевать, наличие *скрытых персонажей*. Скрытый
персонаж - один из тех, чья карта еще не выложена из колоды персонажей в
открытую на стол. Определить наличие скрытого персонажа можно в процессе
расследования, логически, на основе обнаруженных улик. Либо же,
при открытии улики  с прямой ссылкой на этого скрытого
персонажа. При обнаружении улики с сылкой на скрытого персонажа его карта из
колоды персонажей выкладывается в открытую рядом с игровым полем к
картам остальных персонажей. После этого персонаж становится доступным для следственных действий.
В сценарии, в разделе “Ответы”, перечислены все скрытые персонажи.

Персонаж представлен карточкой определенного *цвета* с портретом персонажа.
На карточке также обозначен ID, Имя. Кроме этого сценарий для каждого персонажа представляет дополнение - "Досье",
где описываестя ключевая инфмация о персонаже с точки зрения сценария.

== Движения и действия персонажа

У каждого персонажа во время преступления *в каждый такт* времени есть
только следующие *альтернативные* возможности:

* Перейти в соседнюю локацию и ничего не делать.
* Перейти в соседнюю локацию и выполнить какое либо действие.
* Остаться в локации и выполнить какое либо действие.

Перемещение происходит в смежную локацию при наличие прохода.
Со стороны сценария  возможны какие-либо  ограничения на проход, например
дверь, которую нужно открыть ключем.
В общем случае персонаж может посещать одну и ту же локацию несколько раз в разных
тактах. Для более легких вариантов игры - персонаж может посетить
локацию только один раз.

Путь движения персонажа (последовательность локаций) подразумевается
сценарием, но игрокам явно не раскрывается. Игроки могут определить
этот путь при расследовании.

Пути персонажей раскрываются сценарием в разделе “Ответы” - для каждого
персонажа обозначены его перемещения в виде последовательности номеров
локаций для каждого такта. Эту информацию можно посмотреть в конце игры.

Во время фазы расследования, для визуализации пути (*трека*) движения
персонажа по игровому полю в локации выкладываются жетоны цвета
персонажа. На каждом жетоне номер такта в котором персонаж находился в
локации на которой лежит жетон. Такие жетоны называются жетоны трека
персонажа.


При нахождении в локации персонаж может выполнить какое либо одно действие.
Само действие как сущность механика не предусматривает, но результатом этого действия
становится  *улика*, которая остается либо в локаци, либо у персонажа который совершил
дейсвтвие либо над которым совершено действие.

== Улики

*Улика* - часть сведений о совершенном преступлении, которые
последовательно обнаруживают детективы при расследовании. Улика представлена
карточкой улики, на которой описывается какой
либо физический предмет, событие, какая-то информация, факт. Также может
присутствовать руководство к действию игрока в связи с этой уликой.

Примеры улик: свидетельское показание, мотив, записка, окурок
сигареты, привычка, пристрастие персонажа к курению, факт отсутствия предмета в
локации.

Каждая улика в игре имеет уникальный  идентификатор (номер) например C1, C88 и т.п. На
рубашке карточки улики - ID улики, на обратной стороне -
описание, изображение, признак наличия <<clueparams, параметров>>.

Сценарий преступления определяет набор улик, участвующих в игре
через таблицы связей.

Некоторые из улик могут не иметь отношения к преступлению и служат
для того чтобы усложнить игру. Чем больше таких улик тем сложнее
игра.

Изначально улики скрыты от детективов. В процессе расследования
детективы постепенно “открывают” улики - выкладывают в открытую карты
улик из колоды.

Если в открытой улике есть ссылки на другие улики, эти улики
также открываются (рекурсивно). Сценарий не должен определять глубокую
рекурсию открываемых улик.

[[clueparams]]
== Параметры улик

При открытии карты улики, если на ее карте стоит пиктограмма
“параметры” , то по таблице связей сценария *“Параметры улик”* по
ID улики находятся значения параметров, которые
записывается стираемым маркером на карту улики.

Параметрами улики могут быть: такты, номера локаций, персонажей,
других улик. 

[[virtualclues]]
Помимо этого в качестве значений параметров могут указываться
уникальные произвольные текстовые наименования - *виртуальные
улики*. Этот механизм используется если в сценарии требуется
сослаться на какую то улику, карточки которой нет в игре. В этом
случае используется просто уникальное название виртуальной улики.

В таблице некоторые параметры могут не иметь значений. Это означает что
они точно не известны.

Доступ к таблице параметров возможен только через мастер-прорамму по конкретному ID улики.

Формат таблицы свзей “Параметры улик”

|===
|Улика|Параметры

|C1   |P2, T8, L5
|C2   |L16
|C6   |C=X2 _(<<customclues,кастомная улика>>)_
|C12  |T4
|C13  |S?, T3, C=Кувалда  _(<<virtualclues,виртуальная улика>>)_
|===

Примеры:

* Улика #1 : “Показания. Видел персонажа [S] во время [T] таков в локации [L]”
* Улика #2 : “В этой локации обнаружен скрытый проход в локацию
[L]. Соедините проходом нужные локации. Если проход ведет в
скрытую локацию - выложите эту локацию на поле”
* Улика #6 : “В этой локации отсутствует [С] но
изначально было тут”
* Улика #12 : “Сломанные часы. Стрелка показывает [T] тактов”
* Улика #13 : “В этой локации был замечен персонаж [S] в [T] тактов с [С] в руке”.

[[customclues]]
== Кастомные улики

Сценарием, помимо общих для разных сценариев улик, поставляемых с игрой,
также могут быть предусмотрены *кастомные улики* - их текст полностью
записан в сценарии в виде готовх для печати
карточек, которые можно распечатать перед игрой. Либо альтернативно -
при открытии кастомной улики записать ee текст смываемым маркером на
специальную пустую карточку кастомной улики (или простую бумажку).

Кастомные улики также могут иметь параметры.

Доступ к кастомным уликам сценария есть только через мастер-программу
Каждая кастомная улика имеет уникальный *в пределах сценария* номер с
префиксом “Y”.

Для уменьшения вероятности читерства необходимо чтобы распределение
важности для расследования кастомных улик было такое же как и у
общих, включая процент ложных. Иначе игроки будут или игнорировать
их или наоборот стремится использовать в установлении связей.

== Обыск локации

При проведении расследования детективы могут *“обыскать”* любую открытую локацию (в
том числе и ранее скрытую) чтобы попытаться открыть улики, связанные
с этой локацией. В результате обыска с некоторой вероятностью может быть
"обнаружена" (открыта) улика.

Сценарий задает таблица связей *“Обыск локаций”* которая определяет связь
между локациями и уликами. При обыске используется механика
вероятностного обнаружения улики вместе с механикой *“Фокус обыска”*,
которая позволяет с большей вероятностью обнаружить улику на которую
направлен фокус обыска и получить больше очков.

Кроме этого, обыск может быть двух типов:

* *Обычный* -  не дает гарантии обнаружения улики
* *Детальный* - более дорогой, всегда обнаруживает какую либо из неоткрытых улик

Попытка обыска стоит ресурса. Для каждой локации своя стоимость. За
успешный обыск детективу начисляются очки пропорционально кол-ву
использованных детективом сущностей в фокусе обыска.

Процедура обыска:

. Детектив заявляют о проведении обыска в конкретной локации.
. Опционально - выбирает ключевые сущности в фокусе обыска - их ID.
. Опционально - может объявить обыск *“детальным”*, доплатив ресурс.
. Кидает дайс D12 и по таблице “Обыск локаций” определяют какую улику
следует открыть.

Таблица “Обыск локаций” имеет следующий формат:

|===
|Локация|Стоимость|Детальность 4+|Фокус обыска                       |Сдвиг|Порог|Улика|Очки

|       |         |              |Персонаж |Локация|Улика|Время |     |      |    |
| L1    | 3       |2             | S4           |L3,L4  | -   |T4    |2    |10    |C8  | 1
|  *    | *       | *            | -            |L4     |C5,C6| -    |4    |7     |C3  | 3
| L5    | 4       |2             | -            |   -   | -   |   -  |3    |8     |X12 | 2
|===

*Локация* - id обыскиваемой локации.

*Стоимость* - ресурсная стоимость обычного обыска. Сколько ресурсов тратится
на попытку обыска в локации. Стоимость озвучивается детективу до попытки
обыска. После того как детектив узнает стоимость, он может отказаться от обыска,
при этом ресурс не тратится.

*Детальность* - доплата к стоимости обыска за детальность. Обеспечивает “страховку” от неоткрытия
улики при неудачном броске кубика (см. “Порог”)

*Фокус обыска* - служит для повышения вероятности открытия улик,  имеющих связи
с интересующими детектива сущностями.  В ячейках фокуса перечисляются номера сущностей,
связанных с уликой. Можно через запятую перечислить несколько id  - это
трактуется как любая из них.

Для фокуса обыска детктив может указать *до трех* любых *открытых* сущностей.

*Порог* -  порог обнаружения улики. Число, которое сравнивается с выпавшим на дайсе D12.
Если выпало больше или равное числу в этой колонке (с учетом <<searchshift,сдвига>>),
считается что улика обнаружена. В сценарии порог обнаружения прописывается таким образом, чтобы наиболее
важные для следствия улики имели большие значения порогов.

[[searchshift]]
*Сдвиг* - ставка снижения порога обнаружения. Порог обнаружения снижается за счет фокуса внимания.

*Улика* - номер открываемой улики. Карта обнаруженной улики достается из колоды и выкладывается в
открытую на локацию или рядом. Либо же отдельно, но на локацию кладется
жетон улики с номером улики (чтобы было видно что улика обнаружен в этой локации)

Если все улики локации открыты, на локацию выкладывается жетон
“Обыск невозможен”.

*Очки* - ставка для начисления очков детективу при успешном обыске, *если не сработала "сраховка"
детального обыска*. Если сработала "сраховка" при детальном обыске - очки не начисляются.
Начисляемое количество очков расчитывается по следующиму правилу:

. Одна ставка за успешность обыска (открытие улики).
. При использовании фокуса внимания дополнтельно начисляется:  ставка * количество совпавших сущностей в
фокусе внимания.

== Алгоритмы определения улики в таблице обыска локации

В алгоритмах рассматриваются строки таблицы обыска, относящиеся к выбранной локации. Из рассмотрения
исключаются строки, для которых артефакт уже был открыт в предыдущих обысках.

1) Выполняется упорядочивание строк в соответствии с наличием или отсутствием фокуса внимания.

* Без фокуса внимания -  строки упорядочиваются по убыванию порога обнаружения.
* С фокусом внимания - для каждой строки вычисляется значение N = количеств совпавших сущностей в фокусе внимания
детектива с табличным фокусом внимания. Для всех строк  вычисляются новые значения порогов V = Порог - N * Сдвиг
Строки упорядочиваются по убыванию значений N, V.

2)  Последовательно, начиная с первой строки, идет сравнение порога с числом на дайсе D12. Если на
дайсе *больше или равно* чем таблчный порог - просмотр останавливается, считается что артефакт обнаружен.

3) Если подходящей строки не найдено:

* В случае детального обыска (с доплатой) срабатывает "страхвка"  - в локации открывается улика
с самым низким порогом. Считается что при детальном обыске детектив нашел что-то подозрительное.
* В случае обычного обыска  - объявляется что ничего не найдено.


[[interrogation]]
== Допрос персонажа

Сценарий с каждым из персонажей связывает некоторые улики.
Считается, что часть из этих улик была у персонажа до
преступления, например - одежда, личные вещи. Часть они получили во время
преступления - подобрали в локациях или получили от других персонажей,
например кувалда, записка. Часть улик персонажа описывают их
неотъемлемые черты, например привычки, пристрастие к алкоголю, характер
и т.п. Остальная часть улик - свидетельские показания персонажа.
Сценарий также предполагает, что в процессе преступления персонажи могут
оставлять улики в локациях, передавать/подкидывать другим персонажам
при встрече с ними в одной локации.

Часть улик персонажа может быть известна игрокам (например одежда
и т.п.). Другая часть улик персонажа изначально неизвестна
игрокам. Аналогично процедуре обыска локации, для открытия таких
улик, связанных с персонажем детектив может *“допросить”* любого открытого
персонажа (в том числе и ранее скрытого). В результате допроса может
быть открыта очередная улика персонажа. Детектив “спрашивает”
персонажа об одной или нескольких известных детективу ключевых
сущностях - т.е. определяет *фокус допроса*. Если персонажу “известно” о
них, открывается связанный с этими сущностями улика, который у него есть.
По сути допрос персонажа - проверка гипотез детективов о связи сущностей,
а также возможность выявления новых связанных сущностей.

При ответе персонаж может “сказать неправду” - открывается улика
который на самом деле никак не связан с ключевыми сущностями. Сценарий
регулируют кол-во “ложных” улик

Допрос персонажа стоит ресурса. Для каждого персонажа указывается своя
стоимость. Если игроку при допросе удалось открыть улику ему
начисляется бонус пропорционально количеству сущностей в фокусе допроса детектива.

Для допроса персонажа используется таблица связей “Допрос персонажа”:

|===
|Персонаж |Стоимость  4+|Фокус допроса  |Улика |Бонус

|||Персонаж |Локация |Улика |Время | |
|P1 |3  |P2 |L3 |A4,A5 |T2 |A3|2
|P4 |3|-|-|A4 |T5,T6 |A12 |3
| * | * |P5|-|- |- |A15 |1
|===

*Персонаж* - допрашиваемый персонаж. Детектив на основе известных ему из хода
расследования данных и логических заключений выбирает персонажа которого
нужно допросить.

*Улика*  -  целева улика персонажа, который открывается при успешном допросе.

*Стоимость* -  стоимость допроса персонажа. Сколько тратится ресурса за попытку
допроса персонажа. Стоимость озвучивается детективу до попытки допроса. После того как
детектив узнает стоимость, он может отказаться от допроса, при этом ресурс не тратится.

*Бонус* - бонусная ставка для начисления  бонусов детективу при успешном допросе.
Общее количество бонуса вычисляется по правилу: ставка ++*++ кличество сущностей в фокусе
допроса детектива.

*Фокус допроса* - ключевые сущности связанные с уликой. Детектив на основе
известных из хода расследования данных и логических заключений выбирает
некоторые из *открытых*  сущностей. Для номера нужного персонажа в
таблице в колонках фокуса допроса
ищется набор ключевых сущностей  который в наибольшей степени соответствует набору номеров
выбранных детективом сущностей.

Если такой набор найден - открывается соответствующий ему улика. Этот улика может
быть задан сценарием преднамеренно не верно - имитация того, что персонаж лжет/забыл.

В ячейках фокуса допроса  можно через запятую перечислить несколько номеров -
трактуется как любой из них.

Детектив при выборе ключевых сущностей для фокуса допроса может задавать только по одной
сущности каждого типа.  При этом оне может использовать только *открытые* сущности.

В  фокусе допроса в таблице указываются только те сущности которые
упоминаются в самом целевом улике.

Механика построена таким образом, чтобы детективу, без знания ключевых
улик было бы затруднительно открыть какую либо целевую улику персонажа.

[[targetartalg]]
=== Алгоритм определения целевой улики

Алгоритм определения целевой улики преследует следующую цель:
задавая более конкретный вопрос (с большим количеством сущностей в фокусе допроса)
детектив заработает больше бонуса. Если вопрос детектива
более “общий” ( детектив использует меньшее количество ключевых
сущностей в фокусе допроса) он все равно получит целевую улику но заработает меньше
боуса. В таблице “Допрос персонажа ” улики для локации упорядочены
по важности для раскрытия преступления (самые важные внизу - неважные
вверху)

. В таблице “Допрос персонажа” в колонках фокус допроса, ищется полное совпадение
сущностей с сущностями выбранными детективом для фокуса допроса. Если найдено - открывается
улика. Если не найдено определяется лучшее соответствие.
. При определении лучшего соответствия отбираются все строки которые
содержат все сущности выбранные детективом. Если таких строк нет - опрос
неуспешен. Среди отобранных строк выбирается строка с наименьшим кол-вом
сущностей (т.е. где меньше всего “лишних” сущностей). Если таких строк
несколько - выбирается первая с наименьшей важностью из еще не открытых
улик. Открывается улика соответствующий выбранной строке.

== Экспертиза улик

В случае необходимости подтверждения гипотезы детективы могут заказать
проведение экспертизы для проверки существования связи между *открытми*
сущностями, у которых возможно нет прямых отсылок друг на друга.
Например определить, соответствует ли пепел найденный в
локации сигаретам найденным у персонажа.

В процессе экспертизы с некоторой вероятностью могут быть выявлнны  связи с другими сущностями,
в том числе неоткрытыми. При выявлении связи такие сущности открываются.

Проведение экспертизы стоит определенного ресурса. Величина ресурса для
любой экспертизы постоянна, указывается в сценарии. За успешно найденную связь детективу
начисляется бонус.

Экспертизу можно проводить любое число раз, в т.ч. для одних и тех же сущностей.

Для проведения экспертизы детектив выбирает две и более *открытых* сущности.
Бросает дайс D12. Далее по таблице “Экспертиза сущностей” определяется
выявлена ли связь между указаными сущностями или нет, есть ли дополнительные связи.

Эта таблица доступна только мастеру или через программу.

По завершению экспертизы заполняется карточка “Экспертное заключение”
где указывается номера исследуемых сущностей, результат экспертизы
(установлена связь или нет, допполнительные связи)

Пример таблицы “Экспертиза улик”:

|===
4+|Улики                         |Сдвиг|Порог|Бонус
|Персонаж |Локация|Улика|Время|     |     |

|    P2   |  L3,L5|   -    |  T4 |   2 |10   |3
|    P3   |   -   |  A3,A4 |   - |   4 |7    |4
|===

*Улики* - номера сущностей между которыми есть связь. Для экспертизы детективом в качестве улик заявляются
две или более *открытые* сущности. Далее проверяется совпадение (построчно) табличных улик с заявлеными детективом:

* полное совпадение -  связь выявлена.
* совпало менее двух - связь не выявлена.
* совпало две и более, но не все - связь вывлена частично.

и проверяется “Порог” для возможного открытия дополнительных связей с
другими сущностями.

*Порог* -  порог выявления  *дополнительных* связей.
Число, которое сравнивается с выпавшим на D12, если
на дайсе больше (с учетом "сдвига"), то открываются остальные (все) сущности из колонки "Улики".

*Сдвиг* - величина изменения  порога выявления  дополнительных связей для каждой
вспомогательной сущности.

*Вспомогательные улики* - номера открытых сущностей для помощи экспертизе в выявлении
дополнительных связей. Могут опционально указываться детективом до начала экспертизы.
При их совпадении с табличными уменьшается "Порог" выявления дополнительных связей на величину
“Сдвиг” для каждой совпавшей вспомогательной сущности, либо увеличивается для каждой несовпавшей.
Это моделирует наличие дополнительной информации, что в случае ее полезности делает экспертизу более
"качественной" и наоборот. Детектив может указать не более одной вспомогательной сущности каждого типа.
В таблице в одной ячейке может быть перечислено несколько номеров - это при сопоставлении
трактуется как один из них.

Алгоритм сопоставления вспомогательных сущностей см. нижке.




*Связи* - дополнительные связи с другими сущностями. В случае успешного броска D12
в сравнении с порогом (с учетом "дельты") открываются указанные в этой
колонке сущности.

*Бонус* - бонусная ставка для начисления бонусов детективу при успешной экпертизе.
Начисляемое количество бонуса расчитывается по следующиму правилу:

. Одна ставка за успешность экспертизы  (установление связи).
. Дополнительно по одной ставке за каждую открытую дополнительную связь.

== Алгоритм сопоставления вспомогательных сущностей при экспертизе

Детектив для экспертизы предоставляет не более одной открытой сущности в качестве вспомогательных.

Сравниваются все вспомогательные сущности предоставленные детективом для экспертизы с табличными для
конкретной пары сущностей между которыи проверяется наличие связи.

Если вспомогательная сущность оказалась "полезной"  для экспертизы (совпала с табличной),
то порог уменьшается на значение сдвига.

Если вспомогательная сущность предоставленная детективом  оказалась бесполезной (отсутствует в таблице),
считается что эта информация вредит экспертизе и поэтому к порогу прибавляется значение сдвига.

== Прямые связи сущностей

Прямая связь между любыми сущностями возможна через упоминание в улики а также
в таблице Экспертиза сущностей. Также связи затаюся согласно таблице:
|===
| |Локация |Время |Улика |Персонаж

|Локация |Переходы между локациями| |Обнаружение улики в локации|
|Время | |Соседние такты||
|Улика | | || Обнаружение улики у персонажа
|Персонаж | | | |
|===

== Шаблон сценария
<<script-template-ru.adoc, См. файл script-template.adoc>>

== Руководство по созданию сценария
<<script-guide-ru.adoc, См. файл script-guide-ru.adoc>>