= Zacepco 
Механика детективной игры

© 2026 V. Larionov. Лицензия CC BY 4.0

== О документе

Документ _не_ описывает досконально детали и сюжет игры, а лишь задает общие правила, по которым
должна строится игра. Неотъемлемым дополнением к этой механике служат *сценарии преступления*.
Механика по сути является *фреймворком* детективной игры.

== Сценарий преступления

Сценарий описывает в рамках механики преступление, которое уже произошло. В процессе игры игроки (детективы)
должны раскрыть это преступление. Сценарий ориентируется на разную степень сложности раскрытия преступления,
например совершено одно преступление или сразу несколько. Преступник один или несколько.
У преступника могут быть сообщники. Разное количество действующих лиц, преступление происходит короткое
или длительное время, “театр действия” - маленькая территория или большая и т.п.

Любой сценарий содержит:

* Инструкции для подготовки к началу расследования.
* Информацию для хода расследования.
* Раздел “Ответы”, который можно посмотреть в конце игры.

Готовые сценарии идут с игрой, либо же генерируются специальной
программой.

Игра происходит по одному из сценариев и делится на две *фазы*.

В первой фазе игроки согласно сценария выполняют подготовительные
действия для начала расследования - сборка игрового поля, определение
явных персонажей и др.

Вторая фаза - расследование, кооперативный процесс раскрытия
преступления детективами.

В конце игры выводы следствия сравниваются с разделом “Ответы” сценария.

== Игровые сущности и связи

Сценарий оперирует следующими типами *игровых сущностей*:

* *Персонаж (P)* - действующее лицо в преступлении;
* *Локация (L)* - часть места действия преступления;
* *Артефакт (A)* - часть информации о преступлении;
* *Время (T)* - момент времени в течении преступления;

Сами игровые сущности (кроме времени) представлены карточками сущностей.
Каждая такая карточка, в зависимости от типа сущности имеет свой формат.
Сущность идентифицируется уникальным номером (идентификатором). Время -
не имеет собственных карт, только номер.

Каждая из игровых сущностей может быть связана сценарием с любыми
другими сущностями. С точки зрения связи, когда одна сущность ссылается
на другую, первая называется *ключевой сущностью*, а вторая - *целевой
сущностью*.

Сценарий задает совокупность игровых сущностей и их связей, что по сути
описывает преступление. (Определяет модель преступления).

Часть из этих сущностей и связей могут не относится к преступлению и
служат для усложнения процесса расследования.

Перед началом расследования детективам известна некоторая небольшая
часть сущностей и их связей. В процессе расследования детективы
постепенно открывают остальные карты сущностей и связи.

== Открытие сущностей и связей

В игре используется механика *поэтапного* открытия детективами карт
сущностей и обнаружения связей между ними.

Детективы на основе некоторых уже открытых ключевых сущностей могут узнать
их связи с другими целевыми сущностями, как открытыми, так еще и не
открытыми. Потом отобрать другие ключевые сущности и по ним опять
определить очередные целевые сущности и связи, и так далее.

Связи сущностей, в зависимости от конкретной игровой механики
описываются сценарием в виде** таблиц связей **определенного формата.

При получении информации из этих таблиц, чтобы не раскрыть перед
детективами сразу всю информацию о преступлении, используется
*компьютерная программа*. Либо же ее роль берет на себя один из игроков
(*мастер*), только он может видеть эти таблицы. Так как такой игрок
обладает доступом сразу ко всей информации о преступлении, он _не может_
исполнять роль детектива.

В таблице связей для ключевой сущности может быть не указана конкретная
целевая сущность, а значится - “неизвестно”.

== Элемент случайности

Кубик D12

== Ресурс, бонус

В игре каждое действие детектива стоит определенного *ресурса*. В случае
успешности действия игроку начисляются *бонус*. Сценарий определяет общий
*бюджет* ресурса на расследование. При исчерпании бюджета расследование
завершается _неудачно_.

Индивидуальное кол-во бонуса определяет лучшего детектива в
расследовании.

== Игровое время

Сценарий преступления охватывает какой-то промежуток времени. Время в
этом промежутке течет дискретно, *тактами*, с первого до последнего.
Преступление длится заданное в сценарии число тактов. Чем больше тактов,
тем сложнее раскрыть преступление. Все события в преступлении
привязываются к тактам. Например в такой то такт времени случилось
то-то. Считается что между тактами ничего не происходит.

== Игровое поле, локации, проходы

В сценарии игровое поля определяется в виде графа. В фазе подготовки к
расследованию игроки на основе этого графа из отдельных *локаций* (узлы
графа) собирают игровое поле.

Локация представляет собой квадратную карту. Каждая из локаций имеет
уникальный идентификатор и вид, например: Парковка, Коттедж, Сарай, Бассейн,
Заброшенный дом, Коллектор, Погреб, Беседка, Лес, Лаунж-бар,
Болото,Парковка, Гараж, Пруд, Лодочный домик, Руины, Пещера, Кладбище,
Старый крематорий, Лесопилка, Водопад, Домик лесника, Гостевой дом,
Часовня, Колодец, Оранжерея, Склеп, Конюшня, Овраг, Поляна, Пасика и
т.п.

Определенные локации соединяются между собой *проходами* для персонажа.
Проход может состоять из нескольких карт прохода (сегментов) с разной
конфигурацией прохода (прямой, поворот). Проход всегда соединяет только
две локации. В проходах никогда ничего не происходит, они лишь служат
для указания возможности перемещения персонажей между локациями.

Сценарий также может предполагать наличие *“скрытых” проходов* между
локациями, которые не обозначаются в фазе подготовки к расследованию. О
существовании таких проходов детективы узнают в процессе расследования.
При открытии в какой-то локации *артефакта скрытого прохода* определяется
номер смежной целевой локации в которую ведет проход. На поле выкладывается
карта прохода соединяя
локацию в которой был открыт артефакт скрытого прохода и целевой
локацией.

Скрытый проход может вести в *скрытую локацию*. Это такая локация, о
которой детективы не знают до начала расследования. В качестве скрытой
локации может выступать любая из локаций, еще не включенная в игровое
поле. Обнаруженная скрытая локация выкладывается на игровое поле рядом с
той локацией где был обнаружен артефакт скрытого прохода. Локация
соединяется картой прохода с той локацией где был обнаружен артефакт
скрытого прохода. После открытия скрытой локации на ней можно устраивать
“обыски”

Информация о всех скрытых проходах и локациях явно указывается в разделе
*ответы* сценария.

При разработке сценария должен учитываться смысл локации. Например в
пещере может не быть света, в подвал персонаж может войти только с
ключем, в оранжерее может расти ядовитое растение, бар работает с 3-го
до 6-го такта и др.

== Персонажи

Действующее лицо в преступлении - это *игровой персонаж*. Набор
персонажей в игре определяется сценарием. Сценарий задает явных
персонажей, они известны перед началом расследования. Их карты
выкладываются рядом с игровым полем.

Сценарий может также подразумевать, наличие *скрытых персонажей*. Скрытый
персонаж - один из тех, чья карта еще не выложена из колоды персонажей в
открытую на стол. Определить наличие скрытого персонажа можно в процессе
расследования, логически, на основе обнаруженных артефактов. Либо же,
если при открытии артефакта скрытого персонажа с прямой ссылкой на этого
персонажа. При обнаружении артефакта скрытого персонажа его карта из
колоды персонажей выкладывается в открытую рядом с игровым полем к
картам остальных персонажей. После этого персонажа можно, так же как и
остальных, “допросить” (см "<<interrogation,допрос персонажа>>").
В сценарии, в разделе “Ответы”, перечислены все
скрытые персонажи.

Персонажи представлены карточками. Каждому персонажу соответствует свой
цвет и имя, в качестве номера (идентификатора) - уникальная буква,
первая буква имени.

У каждого персонажа во время преступления в каждый такт времени есть
только две альтернативные возможности:

* Перейти в соседнюю локацию и выполнить какое либо действие.
* Остаться в локации и выполнить какое либо действие.

== Движение персонажа

В каждом такте времени персонаж может либо остаться в локации в которой
находится, либо переместится в смежную по проходу. В общем случае
персонаж может посещать одну и ту же локацию несколько раз в разных
тактах. Для более легких вариантов игры - персонаж может посетить
локацию только один раз.

Путь движения персонажа (последовательность локаций) подразумевается
сценарием, но игрокам явно не раскрывается. Игроки должны определить
этот путь при расследовании.

Пути персонажей раскрываются сценарием в разделе “Ответы” - для каждого
персонажа обозначены его перемещения в виде последовательности номеров
локаций для каждого такта. Эту информацию можно посмотреть в конце игры.

Во время фазы расследования, для визуализации пути (*трека*) движения
персонажа по игровому полю в локации выкладываются жетоны цвета
персонажа. На каждом жетоне номер такта в котором персонаж находился в
локации на которой лежит жетон. Такие жетоны называются жетоны трека
персонажа.

== Артефакты

*Артефакт* - часть сведений о совершенном преступлении, которую
последовательно обнаруживают игроки при расследовании. Артефакт представлен
карточкой артефакта, на которой описывается какой
либо физический предмет, событие, какая-то информация, факт. Также может
присутствовать руководство к действию в связи с этим артефактом.

Примеры артефактов: свидетельское показание, мотив, записка, окурок
сигареты, привычка, пристрастие персонажа к курению, факт отсутствия предмета в
локации.

Каждый артефакт в игре имеет уникальный номер (идентификатор). На
рубашке карточки артефакта - номер артефакта, на обратной стороне -
описание, фото, признак наличия *“параметров”*   (параметры см. ниже).

Сценарий преступления определяет набор артефактов, участвующих в игре
через таблицы связей.

Некоторые из артефактов могут не иметь отношения к преступлению и служат
для того чтобы усложнить игру. Чем больше таких артефактов тем сложнее
игра.

Изначально артефакты скрыты от детективов. В процессе расследования
детективы постепенно “открывают” артефакты (выкладывают в открытую карты
артефактов из колоды).

Если в открытом артефакте есть ссылки на другие артефакты, эти артефакты
также открываются (рекурсивно). Сценарий не должен определять глубокую
рекурсию открываемых артефактов.

== Параметры артефактов

При открытии карты артефактов, если на его карте стоит пиктограмма
“параметры” ✍, то по таблице связей сценария “Параметры артефактов” по
номеру уточняемого артефакта находятся значения параметров, которая
записывается стираемым маркером на карту артефакта.

Параметрами артефакта могут быть такты, номера локаций, персонажей,
других артефактов. 

Помимо этого в качестве артефактов могут указываться
уникальные произвольные текстовые названия чего либо - *виртуальные
артефакты*. Этот механизм используется если в сценарии требуется
сослаться на какой то артефакт, карточки которого нет в игре. В этом
случае используется просто уникальное название виртуального артефакта.

В таблице некоторые параметры могут не иметь значений. Это означает что
они точно не известны.

Формат таблицы “Параметры артефактов”


|===
|Артефакт |Параметры

|A1|P2, T8, L5
|A2 |L16
|A6 |A=С2 (кастомный артефакт)
|A12 |T4
|A13 |P?, T3, A=Кувалда
|===

Примеры:

* Артефакт #1 ✍: “Показания. Видел персонажа [P] во время [T] таков в локации [L]”
* Артефакт #2 ✍: “В этой локации обнаружен скрытый проход в локацию
[L]. Соедините проходом нужные локации. Если проход ведет в
скрытую локацию - выложите эту локацию на поле”
* Артефакт #6 ✍: “В этой локации отсутствует артефакт [A] который
изначально находился тут”
* Артефакт #12 ✍: “Сломанные часы. Стрелка показывает [T] тактов”
* Артефакт #13 ✍: “В этой локации был замечен персонаж [P] в [T] тактов с [A] в руке”.


== Кастомные артефакты

Сценарием, помимо артефактов, поставляемых с игрой, также могут быть предусмотрены
*кастомные артефакты* - их текст полностью записан в сценарии в виде готовх для печати карточек, которые можно распечатать перед игрой. Либо альтернативно - при открытии кастомного артефакта записать его текст смываемым маркером на специальную пустую карточку кастомного артефакта (или простую бумажку).

Доступ к кастомным артефактам сценария есть только у мастер игрока
или программы. Каждый кастомный артефакт имеет уникальный номер с
префиксом “С”. 

Для уменьшения вероятности читерства необходимо чтобы распределение
важности для расследования кастомных артефакты было такое же как и у
стандартных, включая процент ложных. Иначе игроки будут или игнорировать
их или наоборот стремится использовать в установлении связей.


== Обыск локации

При проведении расследования детективы могут *“обыскать”* любую локацию (в
том числе и ранее скрытую) чтобы попытаться открыть артефакты, связанные
с этой локацией. В результате обыска с некоторой вероятностью может быть
открыт артефакт.

В сценарии есть таблица связей “Обыск локаций” которая задает связь
между локациями и артефактами. При обыске используется механика
вероятностного обнаружения артефакта вместе с механикой *“Фокус внимания”*
которая позволяет с большей вероятностью обнаружить артефакт на который
направлен фокус внимания. Таже сам обыск может быть стандартный или *"Тщательный"*

Попытка обыска стоит ресурса. Для каждой локации своя стоимость. За
успешный обыск детективу начисляются бонусы пропорционально кол-ву
использованных детективом сущностей в фокусе внимания.

Детектив заявляют о проведении обыска в конкретной локации. Объявляет
ключевые сущности в фокусе внимания (их номера). Опционально может
объявить обыск *“детальным”* , т.е. более тщательным и дорогим.
Кидает дайс D12 и по таблице “Обыск локаций” определяют какой артефакт
следует открыть.

Таблица “Обыск локаций” имеет следующий формат:


|===
|Обыскиваемая локация 2+|Стоимость обыска|Ставка бонуса 4+|Ключевые сущности в фокусе внимания|Снижение порога |Порог обнаружения |Артефакт

||Базовый|Детальный||Артефакт |Персонаж |Время |Локация |||

|L1 |3|5 |1 |A4 |P3,P4 |- |L4  |-2  |10 |A8
|L5 |3|4 |1 |   |      |  |    | -3 |8  |A12
|===

*Локация* - номер обыскиваемой локации.

*Стоимость обыска* - сколько ресурсов тратится
на попытку обыска в локации. Стоимость озвучивается детективу до попытки
обыска. Детальный обыск - более дорогой обыск, но со “страховкой”, от неоткрытия
артефакта при неудачном броске кубика (см. ниже “порог обнаружения”)

*Ставка бонуса* - сколько бонусов за каждую использованную ключевую
сущность в фокусе внимания получит детектив в случае успешного обыска
{plus}1 ставка за сам факт успешности обыска.

*Порог обнаружения* - число которое сравнивается с выпавшим на дайсе.
Если выпало больше или равное числу в этой колонке (с учетом снижения
порога, см. ниже), считается что артефакт обнаружен. Строки в таблице
упорядочены по убыванию порога обнаружения. Сравнение значений идет
последовательно сверху вниз, до первого успешного обнаружения. Если
какие-то артефакты уже были обнаружены ранее, соответствующие строки
пропускаются.

Если подходящей строки не найдено:

* В случае детального обыска - в локации открывается  артефакт с самым низким порогом. Считается что при детальном обыске детектив нашел что-то подозрительное.
* В случае базового поиска  - объявляется что ничего не найдено.

В сценарии порог обнаружения прописывается таким образом, чтобы наиболее
важные для следствия артефакты имели наименьшую вероятность обнаружения
(большие значения порогов).

*Снижение порога* - порог обнаружения снижается на указанную величину
для каждой ключевой сущности в фокусе внимания. Например если в фокус
внимания N сущностей и величина снижения указана -M то итоговый порог
нужно уменьшить на N++*++M

*Ключевые сущности в фокусе внимания* - Если детектив обозначил фокус
внимания то поиск артефакта идет среди строк, соответствующих фокусу
внимания. Если такого соответствия не выявлено, поиск идет по всем
строкам. При открытии артефакта для поиска которого был обозначен фокус
внимания но соответствие с фокусом не найдено считается что детектив не
нашел что искал, но нашел что-то подозрительное (несоответствие фокусу
внимания понятно детективу из самого найденного артефакта). Для одного и
того же артефакта порог обнаружения с фокусом внимания всегда ниже чем
без фокуса ( см. “Снижение порога” выше ).

Соответствие фокуса внимания определяется по тому же самому алгоритму
что и при обыске персонажа для определения целевого артефакта (см. ниже)

В ячейке можно через запятую перечислить несколько номеров - это
трактуется как любой из них.

Фокус внимания детектива может состоять из любых сущностей *кроме
закрытых* артефактов.

*Артефакт* - номер открываемого артефакта.

Карта обнаруженного артефакта достается из колоды и выкладывается в
открытую на локацию или рядом. Либо же отдельно, но на локацию кладется
жетон артефакта с номером артефакта (чтобы было видно что артефакт
обнаружен в этой локации)

Если все артефакты локации открыты, на локацию выкладывается жетон
“Обыск невозможен”.

== Допрос персонажа [[interrogation]]

Сценарий с каждым из персонажей связывает некоторые артефакты.
Считается, что часть из этих артефактов была у персонажей до
преступления, например одежда, личные вещи. Часть они получили во время
преступления - подобрали в локациях или получили от других персонажей,
например кувалда, записка. Часть артефактов персонажа описывают их
неотъемлемые черты, например привычки, пристрастие к алкоголю, характер
и т.п. Остальная часть артефактов - свидетельские показания персонажей.
Сценарий также предполагает, что в процессе преступления персонажи могут
оставлять артефакты в локациях, передавать/подкидывать другим персонажам
при встрече с ними в одной локации.

Часть артефактов персонажа может быть известна игрокам (например одежда
и т.п.) . Другая часть артефактов персонажа изначально неизвестна
игрокам. Аналогично процедуре обыска локации, для открытия таких
артефактов, связанных с персонажем детектив может “допросить” любого
персонажа (в том числе и ранее скрытого). В результате допроса может
быть открыт очередной артефакт персонажа. Детектив “спрашивает”
персонажа об одной или нескольких известных детективу ключевых
сущностях. Если персонажу “известно” о них, открывается связанный с
этими сущностями артефакт, который у него есть. По сути допрос персонажа
- проверка гипотез детективов о связи сущностей, а также возможность
выявления новых связанных сущностей.

При ответе персонаж может “сказать неправду” - открывается артефакт
который на самом деле никак не связан с ключевыми сущностями. Сценарий
регулируют кол-во “ложных” артефактов

Допрос персонажа стоит ресурса. Для каждого персонажа указывается своя
стоимость. Если игроку при допросе удалось открыть артефакт ему
начисляется бонус пропорционально количеству заявленных детективом
ключевых сущностей.

Для допроса персонажа используется таблица связей “Допрос персонажа”:


|===
|Допрашиваемый персонаж |Стоимость допроса |Ставка бонуса 4+|Ключевые сущности связанные с артефактом |Целевой артефакт персонажа 

||||Локация |Такт |Артефакт |Персонаж | 
|P1 |3 |2 |L2 |T3 |A4,A5 | |A45
| | ||||A4 |P5,P6 |A12 
|===

*Допрашиваемый персонаж*- детектив на основе известных ему из хода
расследования данных и логических заключений выбирает персонажа которого
нужно допросить.

*Стоимость допроса*- сколько начисляется траты ресурса за попытку
допроса персонажа. Стоимость озвучивается детективу до попытки допроса.

*Ставка бонуса* - сколько бонусов за каждую использованную ключевую
сущность связанную артефактом получит детектив в случае успешного
допроса.

*Ключевые сущности связанные с артефактом* -детектив на основе
известных из хода расследования данных и логических заключений выбирает
некоторые из *известных* сущностей - любых сущностей *кроме закрытых*
артефактов. Для номера нужного персонажа в таблице ищется набор ключевых
сущностей который в наибольшей степени соответствует набору номеров
выбранных детективом сущностей. Если такой набор найден - открывается
соответствующий ему артефакт. Такой артефакт может быть задан сценарием
преднамеренно не верно - имитация того, что персонаж лжет/забыл как было
на самом деле.

В ячейке можно через запятую перечислить несколько номеров - это
трактуется как любой из них

В наборе ключевых сущностей указываются точно те сущности которые
упоминаются в самом целевом артефакте.

Механика построена таким образом, чтобы детективу, без знания ключевых
артефактов было бы затруднительно открыть какой либо артефакт персонажа.

Алгоритм определения целевого артефакта преследует следующую цель:
задавая более конкретный вопрос (с большим количеством ключевых
сущностей) детектив заработает больше бонуса. Если вопрос детектива
более “общий” ( детектив использует меньшее количество ключевых
сущностей) он все равно получит целевой артефакт но заработает меньше
боуса. В таблице “Допрос персонажа ” артефакты для локации упорядочены
по важности для раскрытия преступления (самые важные внизу - неважные
вверху)


. В таблице “допрос персонажа” ищется полное совпадение сущностей с
сущностями выбранными детективом для опроса. Если найдено - открывается
артефакт. Если не найдено определяется лучшее соответствие.
. При определении лучшего соответствия отбираются все строки которые
содержат все сущности выбранные детективом. Если таких строк нет - опрос
неуспешен. Среди отобранных строк выбирается строка с наименьшим кол-вом
сущностей (т.е. где меньше всего “лишних” сущностей). Если таких строк
несколько - выбирается первая с наименьшей важностью из еще не открытых
артефактов. Открывается артефакт соответствующий выбранной строке.

== Экспертиза артефактов

Цель экспертизы - выявить наличие связи между найденными артефактами.
Экспертиза предназначена для выявления связи между артефактами у которых
нет отсылок на другие артефакты.

В случае необходимости подтверждения гипотезы детективы могут обратится
к экспертам для проверки существования связи между найденными
артефактами. Например определить, соответствует ли пепел найденный в
локации сигаретам найденным у персонажа.

Проведение экспертизы стоит определенного ресурса. Величина ресурса для
любой экспертизы постоянна. За успешно найденную связь детективу
начисляется бонус пропорционально кол-ву пигодившихся вспомогательных
сущностей.

Для проведения экспертизы детектив выбирает *два* открытых артефакта.
Опционально может выбрать известные вспомогательные сущности которые
могут помочь экспертизе. Также решает какого уровня будет экспертиза.
Бросает дайс D12 и по таблице “Экспертиза артефактов” определяется
выявлена ли связь или нет. Эта таблица доступна только мастеру или через
программу. Бросок дайсов имитирует сложность экспертизы.

По завершению экспертизы заполняется карточка “Экспертное заключение”
где указывается номера исследуемых артефактов и результат экспертизы
(установлена связь или нет)

Пример таблицы “Экспертиза артефактов”:


|===
2+|Анализируемые артефакты 4+|Вспомогательные сущности |Снижение порога 2+|Порог выявления |Ставка бонуса 

|||Локация |Такт |Артефакт |Персонаж ||Базовый |Расширен |

|A2 |A4 |L7 |T3,T4 | | |-2 |5 |12 |1
|A4 |A3 |L1 | | | |-1 |2 |1 |2
|===

*Анализируемые артефакты* - Номера артефактов между которыми
проверяется наличие связи. Для экспертизы всегда должно быть заявлено 2
открытых артефакта. Если в таблице нет совпадений с номерами выбранных
детективом артефактов, объявляется - связь не выявлена. Если есть -
проверяем “Порог выявления”

*Вспомогательные сущности*- могут опционально указываться детективом.
При их совпадении с табличными уменьшается порог выявления на величину
“Cнижение порога” для каждой совпавшей сущности. Это моделирует наличие
дополнительной информации, что упрощает экспертизу. Детектив может
указать не более одной вспомогательной сущности каждого типа.

*Снижение порога* - величин снижения порога выявления для каждой
совпавшей вспомогательной сущности. От значения порога для выбранного
типа экспертизы отнимается значение снижения порога столько раз, сколько
совпало вспомогательных сущностей

*Порог выявления*- число, которое сравнивается с выпавшим на D12, если
на дайсе больше, то объявляется что связь между артефактами выявлена.
Если порог выше чем выпало на дайсе, объявляется - связь не обнаружена.
Порог зависит от уровня экспертизы - Базовый, Расширенный. Перед
проведением экспертизы детектив может выбрать какой уровень
использовать.Чем выше уровень тем ниже порог выявления, но выше
стоимость экспертизы (больше ресурса). Если уровень не указан всегда
используется базовый. Если детектив хочет сэкономить - указывает
начальный. Стоимость уровня экспертизы указывается в сценарии.с

Порог в сценарии не должен указываться слишком высоким, чтобы не вносить
большой элемент случайности.

Ставка бонуса - сколько детективу будет начислено бонусов за каждую
совпавшую вспомогательную сущность {plus}1 ставка за факт успешного
выявления связи

== Прямые связи сущностей

|===
| |Локация |Время |Артефакт |Персонаж

|Локация |Переходы между локациями; 
Упоминание в артефакте |Упоминание в артефакте |Обнаружение артефакта в локации; Упоминание в артефакте |Упоминание в артефакте
|Время | |Соседние такты; Упоминание в артефакте |Упоминание в артефакте |Упоминание в артефакте
|Артефакт | | |Упоминание в артефакте| Обнаружение артефакта у персонажа; Упоминание в артефакте
|Персонаж | | | |Упоминание в артефакте
|===

==  Преступление, начало расследования

Стандартный сценарий преступления - убийство - моделируется следующим
образом:

* Задается локация где произошло преступление. Эта локация является
начальной точкой расследования.
* На локацию в открытую выкладывается артефакт преступления в котором
описаны некоторые связи с другими сущностями - ссылку на персонажа
которого убили, время убийства.
* Дополнительно на карточку персонажа трупа могут быть в открытую
выложенные какие то дополнительные артефакты, означающие что обнаружено
на трупе.
* Дополнительно на карточки некоторых персонажей могут быть выложены
некоторые общедоступные артефакты.

Детективы, исходя из начально открытых артефактов продолжают
расследование, путем построения дедуктивных гипотез, обыска локаций и
допроса персонажей.

Ход расследования предполагает, что улики должны находиться
последовательно, т.е. одни найденные улики должны указывать на другие и
так пока не приведут к преступнику. Логичным первым шагом является обыск
места преступления.

== Шаблон сценария
<<script-template.ru, См. шаблон>>

== Практические приемы для сценариев.

Связь локаций по перемещению артефактов из одной локации в другую. В
одной локации найден предмет, изначально находящийся в другой.

Связь персонажа с локацией через связь артефактов. Например окурок
сигареты в локации и пачка сигарет у персонажа:

* Артефакт в локации L1 - A1: Окурок сигареты марки ++[++Camel++]++
* Артефакт у персонажа P1 - A2: Пачка сигарет марки ++[++Camel++]++

____
____

Сценарий также может определять в какой локации артефакт был изначально
до преступления и потом пропал из нее. Такой факт описывается в виде
другого артефакта. Например Артефакт # 66: “В этой локации отсутствует
артефакт A++[__]++. Хотя ранее он в ней находился”.

Привязка артефактов к последовательности тактов.

Связь через процесс? Например молотком забивать гвозди?

Сигарета - пачка : часть-целое

Условные улики - указывает на что то при условии что есть определенная
другая улика. Например в такой-то локации найдена сигарета такой-то
марки. И второй артефакт - такой то персонаж курит сигареты такой-то
марки.

Расследование всегда начинается с локации места преступления, например
локации, где обнаружен труп.

Не все артефакты в игре могут иметь отношение к преступлению, часть из
них для расследования бесполезна. Для сценариев с легкой сложностью все
клики имеют отношение к преступлению (из игры исключаются бесполезные
артефакты)

Некоторые возможные стратегии поиска клик:

* Детектив знает что искать но не знает где
* Детектив не знает что искать но знает где
* Неуместные артефакты - предмет которого не должно быть в данной
локации

# Взаимодействие персонажей

Если персонажи находятся одновременно в локации, персонаж может что то
сказать другому персонажу, например, что он собирается делать, или
передать предмет.

Персонаж если находился в одной локации с другим персонажем дает об этом
показания. Если в соседней - дает показания что кого-то видел в такой то
клетке, без конкретизации кого именно.

Камеры установленные в локации дают полный лог того что происходило в
локации.

Персонаж может находиться в локации какое-то время и находясь в локации
персонаж может что-то в ней делать. Для каждого вида локации и роли
персонажа определен список действий персонажа в локации?

Нужно ли вводить сущность действия персонажа?

Например - кто угодно может плавать в бассейне. На кухне повар может
готовить.

Если инспектор спрашивает что вы там делали персонаж отвечает.
