= Zacepco - Механика детективной игры

© 2026 V. Larionov.  
Лицензия CC BY 4.0

== О документе

Документ описывает механику детективной игры, задаёт общие правила, по которым она должна строиться.  
Для целостности игры неотъемлемым дополнением к этой механике являются *сценарии преступления*, которые описывают сюжетную составляющую.  
Сама механика по сути является *фреймворком* дедуктивной детективной игры с элементами случайности.

== Сценарий преступления

Сценарий в рамках механики описывает преступление, которое уже произошло.  
В процессе игры игроки (детективы) должны раскрыть это преступление.  
Сценарий ориентируется на разную степень сложности раскрытия преступления, описывая, например, одно преступление или сразу несколько, с участием одного или нескольких преступников, с наличием или отсутствием сообщников, с разным количеством подозреваемых, длительностью преступления, размером «театра действий» и т. п.

Любой сценарий содержит:

* Инструкции для подготовки к началу расследования.
* Информацию для хода расследования.
* Раздел «Ответы», который можно посмотреть в конце игры.

Готовые сценарии идут с игрой либо же генерируются специальной программой.

Игра происходит по выбранному игроками сценарию и делится на две *фазы*.

В первой фазе игроки согласно сценарию выполняют подготовительные действия для начала расследования: сборку игрового поля и др.

Вторая фаза — расследование, кооперативный процесс раскрытия преступления детективами.

В конце игры выводы следствия сравниваются с разделом «Ответы» сценария.

== Мастер-программа

Для модерации процесса игры используется компьютерная программа — *«Мастер-программа»*, которая настраивается сценарием под конкретную игру.  
Программа также автоматизирует все расчёты, связанные с игровым процессом, и контролирует игровые механики.

== Игровые сущности и связи

Сценарий оперирует следующими типами *игровых сущностей*:

* *Персонаж ( P )* — действующее лицо в преступлении;
* *Локация ( L )* — часть места преступления;
* *Улика ( C )* — часть информации о преступлении;
* *Время ( T )* — момент времени в течение преступления.

Сами игровые сущности (кроме времени) представлены карточками сущностей.  
Каждая такая карточка в зависимости от типа сущности имеет свой формат.  
Сущность идентифицируется уникальным идентификатором, состоящим из буквы - типа сущности и уникального номера. Например P2, L5, C55.

Время не имеет собственных карт, только порядковый номер (T1, T2, …).

Каждая из игровых сущностей может быть связана сценарием с любыми другими сущностями.  
С точки зрения связи, когда одна сущность ссылается на другую, первая называется *ключевой сущностью*, а вторая — *целевой сущностью*.

Сценарий задаёт совокупность игровых сущностей и их связей, что по сути описывает преступление (определяет модель преступления).

Часть из этих сущностей и связей могут не относиться к преступлению и служить для усложнения процесса расследования (ложные улики).

Перед началом расследования детективам известна некоторая небольшая часть сущностей и их связей.  
В процессе расследования детективы постепенно открывают остальные сущности и связи.

В игре сущности представлены карточками. Часть карточек сущностей, которые используются в сценарии, являются уже готовыми — *«референсные сущности»*, а часть требуют изготовления — *«кастомные сущности»*. Они находятся в виде макетов в сценарии, их нужно распечатать самостоятельно перед игрой. Референсные сущности могут быть переиспользованы в разных сценариях; при необходимости сценарий определяет кастомные сущности.

== Открытие сущностей и связей

В игре используется механика *поэтапного* открытия детективами карт сущностей и обнаружения связей между ними.

Детективы на основе некоторых уже открытых ключевых сущностей могут узнать их связи с другими целевыми сущностями, как открытыми, так и ещё не открытыми.  
Потом выбрать другие ключевые сущности и по ним снова определить очередные целевые сущности и связи, и так далее.

Связи сущностей в зависимости от конкретной игровой механики описываются сценарием в виде *таблиц связей* определённого формата.

При получении информации из таблиц связей, чтобы не раскрыть перед детективами сразу всю информацию о преступлении, используется *мастер-программа*.

== Элемент случайности

Дайс D12.

== Ресурс, очки

В игре каждое действие детектива стоит определённого *ресурса*.  
В случае успешности действия игроку начисляются *очки*.  
Сценарий определяет общий *бюджет* ресурса на расследование.  
При исчерпании бюджета расследование останавливается, детективы должны сделать выводы по имеющимся данным и сравнить результаты с ответами.

Индивидуальное количество заработанных очков определяет лучшего детектива в расследовании.

== Игровое время

Сценарий преступления охватывает какой-то промежуток времени.  
Время в этом промежутке течёт дискретно, *тактами*, с первого до последнего (T1, T2,...Tn).  
Преступление длится заданное в сценарии число тактов.  
Чем больше тактов, тем сложнее раскрыть преступление.  
Все события в преступлении привязываются к тактам.  
В каждый такт времени происходит что-то.  
Считается, что между тактами ничего не происходит.

== Место преступления, локации, переходы

В сценарии место преступления определяется в виде графа.  
В фазе подготовки к расследованию игроки на основе этого графа из отдельных *локаций* (узлы графа) собирают место преступления — сцену. Сцена представляет собой сетку определённого размера (размер сетки задаётся сценарием). В любую ячейку сетки сцены помещается локация. Некоторые ячейки сцены могут быть оставлены пустыми.

Каждая локация представлена квадратной карточкой локации (референсной или кастомной). Карточка локации содержит следующую информацию:

* ID;
* Название;
* Описание;
* Изображение локации.

Смежные локации могут соединяться между собой *переходами* для персонажа.  
Если требуется соединить переходом не смежные локации, используются карты переходов с разной конфигурацией (прямой, поворот, Т-образный), которые выкладываются в пустые ячейки сцены, соединяя нужные локации.  
В самом переходе никогда ничего не происходит, он лишь служит для указания возможности перемещения персонажей между локациями.  
Если нужно смоделировать поведение персонажа в переходе (например, время в пути, какие-то действия), то он заменяется полноценной локацией.

Сценарий также может предполагать наличие *«скрытых» переходов* между локациями, которые не обозначаются в фазе подготовки к расследованию.  
О существовании таких переходов детективы узнают в процессе расследования.  
При открытии в какой-то локации улики указывающей на наличие скрытого перехода (*улика скрытого перехода*) определяется ID целевой локации, в которую ведёт переход.  
На сцену выкладывается карта перехода, соединяющая локацию, в которой была открыта улика скрытого перехода, с целевой локацией.

Скрытый переход может вести в *скрытую локацию*.  
Это такая локация, о которой детективы не знают до начала расследования.  
В качестве скрытой локации выступает одна из *референсных* локаций, ещё не выложенная на сцену.  
Обнаруженная скрытая локация выкладывается на сцену в указанную в сценарии ячейку.  
Локация соединяется переходом с той локацией, где была обнаружена улика скрытого перехода.  
После открытия локация становится доступной для следственных действий.

Информация о всех скрытых переходах и локациях включена в *ответы* сценария.

При разработке сценария локации должны определяться таким образом, чтобы учитывался их смысл в расследовании.  
Например, в пещере может не быть света, в подвал персонаж может войти только с ключом, в оранжерее может расти ядовитое растение, бар работает с 3-го по 6-й такт и др.  
Смысловая нагрузка и описание локации должны помогать детективам в расследовании.

Сценарий для каждой локации описывает журнал событий (log) этой локации для каждого такта времени.  
В событии лога содержится информация о том, какие персонажи находились в этой локации, какие улики оставили или забрали из локации (улики взаимодействовавшие с локацией).

Журнал событий используется в конце игры при проверке выводов следствия и недоступен игрокам в процессе следствия.

== Персонажи

Действующее лицо в преступлении — это *персонаж*.  
Каждый персонаж представлен (референсной или кастомной) карточкой персонажа.  
Карта персонажа содержит следующую информацию:

* ID;
* Имя;
* Досье (описание);
* Изображение персонажа.

Набор персонажей в игре определяется сценарием.  
Сценарий задаёт явных персонажей — они известны перед началом расследования.  
Их карты выкладываются рядом с игровым полем.

Сценарий может также подразумевать наличие *скрытых персонажей*.  
Скрытый персонаж — один из тех, чья карта ещё не выложена из колоды персонажей в открытую на стол.  
В качестве скрытого персонажа выступает один из *референсных* персонажей.

Определить наличие скрытого персонажа можно в процессе расследования логически, на основе обнаруженных улик, либо же при открытии улики с прямой ссылкой на этого скрытого персонажа (аналогично уликам, укащывающим на скрытый переход).  
При обнаружении улики со ссылкой на скрытого персонажа его карта из колоды персонажей выкладывается в открытую рядом с игровым полем к картам остальных персонажей.  
После этого персонаж становится доступным для следственных действий.

В сценарии, в разделе «Ответы», перечислены все скрытые персонажи.

Персонажи в сценарии должны описываться таким образом, чтобы это описание помогло детективам в расследовании.

== Движения и действия персонажа

У каждого персонажа во время преступления *в каждый такт* времени есть только следующие возможности:

* Перейти в соседнюю локацию или остаться в текущей.
* Находясь в локации, выполнить какое-либо *одно* действие либо ничего не делать.

Перемещение происходит в соседнюю локацию при наличии перехода.  
Со стороны сценария возможны какие-либо ограничения на переход, например дверь, которую нужно открыть ключом.  
В общем случае персонаж может посещать одну и ту же локацию несколько раз в разных тактах.  
Для более лёгких вариантов игры персонаж может посетить локацию только один раз.

Путь движения персонажа (последовательность локаций) подразумевается сценарием, но игрокам явно не раскрывается.  
Игроки могут определить этот путь при расследовании.

Пути персонажей раскрываются сценарием в разделе «Ответы»: для каждого персонажа обозначены его перемещения в виде последовательности ID локаций для каждого такта (в журнале персонажа).  
Эту информацию можно посмотреть в конце игры.

Во время фазы расследования для визуализации пути (*трека*) движения персонажа по игровому полю в локациях выкладываются жетоны цвета персонажа.  
На каждом жетоне — номер такта, в котором персонаж находился в локации, на которой лежит жетон.  
Такие жетоны называются жетонами трека персонажа.

При нахождении в локации персонаж может выполнить какое-либо *одно* действие.  
Само действие как сущность механика не предусматривает, но результатом этого действия становится *улика*, которая связывается либо с локацией, либо с персонажем.

Сценарий для каждого персонажа описывает журнал событий (log) этого персонажа для каждого такта времени.  
В событии лога содержится информация о том, в какой локации находился персонаж и с какой уликой взаимодействовал (например, оставил след или на персонаже остался след).

Журнал событий используется в конце игры при проверке выводов следствия и недоступен игрокам в процессе следствия.

== Улики

*Улика* — часть сведений о совершённом преступлении, которые последовательно обнаруживают детективы при расследовании.  
Уликой может быть какой-либо физический предмет, событие, какая-то информация, факт.

Примеры улик: свидетельское показание, мотив, записка, окурок сигареты, привычка, пристрастие персонажа к курению, факт отсутствия предмета в локации, лабораторное заключение.

Сценарий преступления определяет набор улик, участвующих в игре.  
Улика представлена (референсной или кастомной) картой улики с напечатанным на ней:

* ID;
* Название;
* Описание (детальное);
* Изображение улики.

Некоторые из улик могут не иметь отношения к преступлению и служить для того, чтобы усложнить игру (ложные улики). Чем больше таких улик, тем сложнее игра.

Изначально улики скрыты от детективов.  
В процессе расследования детективы постепенно «открывают» улики — выкладывают в открытую карты улик.

Если в открытой улике есть ссылки на другие еще не открытые сущности, эти сущности также открываются (рекурсивно). Сценарий не должен определять глубокую рекурсию открываемых сущностей.

Примеры улик:

* Улика C1: «Показания. Видел персонажа P1 (Горничная) во время 4-го такта в локации L2 (Столовая)».
* Улика C2: «В этой локации обнаружен скрытый проход в локацию L4 (Подвал)».
* Улика C6: «В этой локации отсутствует С2 (Подсвечник), но изначально был тут».
* Улика C12: «Сломанные часы. Стрелка показывает T8 тактов».
* Улика C13: «В этой локации был замечен персонаж P1 (Садовник) в T3 такта с C6 (Нож) в руке».

== Переменные значения

Для универсализации печатных карточек сущностей в них вместо конкретных значений/текста указываются имена переменных, значения которых определяются в сценарии.

Пример использования переменных для улики:

====
C1: Видел персонажа $P во время $T такта в локации $L
====

Значения P, T, L берутся из сценария.

====
L2: Локация $N. Описание: $D
====

Название N и описание D берутся из сценария.

== Переиспользование сущностей, референсные и кастомные сущности

Сценарий может использовать некоторые сущности из других сценариев.  
Для этого в сценарии указывается, из каких сценариев будут использоваться сущности. Для этих «импортируемых» сущностей создаются «локальные» сущности (как обычные сущности сценария), в которых указывается референс на импортированную сущность.  
Такие сущности называются *референсными*.

Все сущности сценария, у которых отсутствуют референсы на импортируемые сущности, считаются *кастомными сущностями* (локальными сущностями сценария) и печатаются перед началом игры.

== Обыск локации

При проведении расследования детективы могут *«обыскать»* любую открытую локацию (в том числе и ранее скрытую), чтобы попытаться открыть улики, связанные с этой локацией.  
В результате обыска с некоторой вероятностью может быть «обнаружена» (открыта) улика.

Сценарий задаёт таблицу связей *«Обыск локаций»*, которая определяет связь между локациями и уликами.  
При обыске используется механика вероятностного обнаружения улики вместе с механикой *«Фокус обыска»*.  
Фокус позволяет с большей вероятностью обнаружить улику, на которую направлен фокус обыска, и получить больше очков.  
Однако стратегическая цель фокуса — скорее не «получить» улику, а больше *сформулировать гипотезу для проверки*.  
Фокус состоит из двух частей: табличный фокус (референсный) и фокус детектива.

Обыск локации стоит определённого ресурса. За обыск детективу могут быть начислены очки.

Процедура обыска:

1. Детектив заявляет о проведении обыска в конкретной локации, например L1.
2. Указывает фокус детектива — набор ID любых *открытых* сущностей или любых типов, например: T4, L?, C?.
3. Кидает дайс D12 для моделирования вероятностного характера обнаружения улики.
4. По таблице «Обыск локаций» определяется результат обыска.  
   Доступ к таблице обыска осуществляется через мастер-программу.

=== Таблица связей «Обыск локаций»

|===
|Локация |Фокус           |Порог|Улика
| L1     | P4, L3, L4, T4 |5.2  |С8
|  *     | L4, С5, С6     |5.0  |С3
| L5     |     L6         |8.0  |С12
|===

*Локация* — ID обыскиваемой локации.

[[search-focus]]  
*Фокус* — табличный фокус обыска. Служит для повышения вероятности открытия улик, имеющих связи с целевыми сущностями, интересующими детектива.  
В табличном фокусе перечисляются только _ID_ сущностей, связанных с целевой уликой.  
Указание отдельных типов в табличном фокусе не допускается.  
Можно через запятую перечислить несколько ID одинакового типа — это трактуется как любой из них.

Фокус детектива может состоять из одного или нескольких ID *открытых* сущностей или любых типов сущностей.  
Например: «P1, C1, T?». Максимальное количество элементов в фокусе детектива определяется в сценарии (обычно 3).

*Порог* — порог обнаружения улики. _Действительное_ число, которое сравнивается с выпавшим на дайсе D12.  
Если выпало меньше «Порога», считается, что сыграли негативные факторы и целевая улика не обнаружена.  
В сценарии порог обнаружения задаётся таким образом, чтобы наиболее важные для следствия улики имели большие значения порогов. Возможность указания дробных значений позволяет «тонко» упорядочить улики.

Для уменьшения влияния случайности нужно указывать малые значения порогов; для исключения случайности — меньше 1.

*Улика* — ID целевой улики. Карта обнаруженной улики выкладывается в открытую. Для обозначения места, где была найдена улика, на локацию выкладывается жетон с ID открытой улики.

=== Стоимость обыска, начисление очков

[[search-cost]]  
*Стоимость обыска* — ресурсная стоимость обыска для любых локаций одинакова и определяется в сценарии.  
Определяет, сколько ресурсов тратится за обыск в локации. Стоимость детектив узнаёт в начале игры.

[[search-points]]  
*Очки за обыск* — базовое количество очков, которые могут быть начислены детективу за обыск локации.  
Для всех локаций в сценарии определяется одинаковое базовое количество очков.  
Базовые очки начисляются за открытие улики, но только если она _НЕ_ была *<<accidental-discovery, случайно обнаружена>>*.  
При начислении базовых очков дополнительно начисляется по одному очку за каждое совпадение _сущности_ в фокусе детектива с таличным.

== Алгоритм определения целевой улики в таблице обыска локации

Цель алгоритма: определить улику, наиболее соответствующую фокусу детектива и броску D12.

В алгоритме рассматриваются только строки таблицы обыска, относящиеся к выбранной локации.  
Из рассмотрения исключаются строки, для которых улика уже была открыта в предыдущих обысках.

1. Для каждой строки вычисляются веса фокуса EQ, EQT, NE (см. <<focus-weights-comp, вычисление весов соответствия фокусов>>).
2. Строки таблицы упорядочиваются по убыванию «EQ», убыванию «EQT», возрастанию «NE», убыванию *Порога*.
3. Последовательно, начиная с первой строки, идёт сравнение «Порога» с числом на дайсе D12.
4. Если значение D12 >= «Порог», просмотр останавливается. Улика обнаружена, она открывается.  
   Сообщается, сколько очков начислено детективу.

[start=5]
[[accidental-discovery]]  
5. Если подходящей строки не найдено (значение D12 недостаточно), происходит *«Случайное обнаружение»* улики.  
   Открывается улика с самым низким порогом среди рассматриваемых (ещё не открытых улик).  
   Сообщается, что случайно обнаружена подозрительная улика.
6. Сообщается о совпадающих элементах (сущности + типы) _фокуса детектива_ с табличным фокусом открытой улики:
   * Совпавшие ID сущностей и типы в фокусе детектива;
   * Типы ID не совпавших сущностей в табличном фокусе.

====
Например, для фокуса детектива «P2, T4, C?» и табличного фокуса «P1, P2, T4, L2» будет выведено:  
«В локации L1 была найдена улика C2, связанная с P2, T4, P?, L?».
====

[start=7]
7. Если все улики локации открыты, на локацию выкладывается жетон «Все улики обнаружены». Дальнейшие обыски локации невозможны.

[[focus-weights-comp]]  
=== Вычисление весов соответствия фокусов

Вычисляются следующие значения весов соответствия фокусов детектива и табличного:

* EQ = [количество совпавших ID сущностей в фокусах],
* EQT = [количество совпавших типов в фокусах],
* NE = [количество *НЕ* совпавших сущностей или типов] в фокусе обыска детектива и табличном фокусе.

Сначала вычисляется «EQ» путём сопоставления ID в обоих фокусах. Далее исключаются совпавшие ID из обоих фокусов.  
Для вычисления «EQT» сравниваются прямо указанные в фокусе детектива типы сущностей (P?, L?, …) с типами оставшихся в табличном фокусе ID сущностей. Совпавшие при вычислении «EQT» элементы исключаются из обоих фокусов.  
«NE» вычисляется как суммарное количество оставшихся сущностей в фокусах.

При вычислении «EQT» элемент типа «X?» в фокусе детектива считается совпавшим с сущностью табличного фокуса (с ID), если тип «X?» соответствует типу в ID сущности.

Например, фокус детектива P1, P2, T? в сравнении с табличным P2, T4, C1 даёт:  
EQ = 1 (для P2), EQT = 1 (для T?), NE = 2 (для P1, C1).

[[interrogation]]  
== Допрос персонажа

Сценарий с каждым из персонажей связывает некоторые улики.  
Считается, что часть из них была у персонажа до преступления (например, одежда, личные вещи, характер).  
Часть они получили во время преступления — подобрали в локациях или получили от других персонажей (например, нож, записка).  
Часть улик персонажа описывают их неотъемлемые черты (например, привычки, пристрастие к алкоголю, характер и т.п.). Остальная часть улик — свидетельские показания персонажа.  
Сценарий также предполагает, что в процессе преступления персонажи могут оставлять улики в локациях, передавать или подкидывать другим персонажам при встрече с ними в одной локации.

Часть улик персонажа может быть известна детективам (например, одежда и т.п.) до расследования.  
Другая часть улик — скрыта.

Аналогично процедуре обыска локации, для открытия таких улик, связанных с персонажем, детектив может *«допросить»* любого открытого персонажа (в том числе и ранее скрытого).  
В результате допроса может быть открыта очередная улика персонажа и установлена связь с другими уликами.

Во время допроса детектив «спрашивает» персонажа об известных следствию фактах (открытых ключевых сущностях) или о гипотезах следствия (о любых типах сущностей) — то есть определяет *фокус допроса*.  
Если персонажу «известно» что-либо об этом, открывается связанная с фокусом улика и её связи.  
Механика допроса построена таким образом, чтобы детективу без знания ключевых сущностей или их типов было затруднительно открыть релевантную целевую улику персонажа.

При ответе персонаж может *«сказать неправду»* — открывается улика, которая на самом деле никак не связана с ключевыми сущностями в фокусе допроса.  
Сценарий регулирует количество «ложных» улик. Ложность улики может быть установлена только при дедуктивном анализе.  
В разделе «Ответы» перечисляются, какие улики были действительно ложными.

Каждый персонаж в той или иной степени не желает делиться определённой информацией, а детектив использует психологическое давление, чтобы получить максимум информации.  
Это взаимодействие имеет случайный характер и моделируется с помощью броска D12.

Допрос персонажа стоит определённого ресурса. За допрос детективу могут быть начислены очки.

Сценарий задаёт таблицу связей *«Допрос персонажа»*, которая определяет связь между персонажами и уликами.

Процедура допроса:

1. Детектив выбирает персонажа, которого будет допрашивать, например P1.
2. Указывает фокус детектива — набор ID любых *открытых* сущностей или любых типов, например L1, P?.
3. Бросает D12 для моделирования психологического давления на персонажа.
4. По таблице допроса определяется результат допроса.  
   Доступ к таблице допроса осуществляется через мастер-программу.

=== Таблица связей «Допрос персонажа»

|===
|Персонаж |Фокус             |Порог |Улика
|P1       |P2, L3, C4, С5, T2| 3.0  |C3
|P4       |C4, T5, T6        | 5.0  |C12
| *       |P5                | 5.2  |C15
|===

*Персонаж* — допрашиваемый персонаж.  
Детектив на основе известных ему из хода расследования улик и логических заключений выбирает персонажа, которого нужно допросить.

*Фокус* — табличный фокус допроса (то же, что и <<search-focus, табличный фокус обыска>>).

На фокус детектива налагается ограничение:  
*Среди элементов фокуса детектива обязательно должен быть как минимум один ID сущности.*

*Порог* — порог сопротивления психологическому давлению детектива.  
_Действительное_ число, которое сравнивается с выпавшим на дайсе D12.  
Если выпало меньше «Порога», считается, что детектив не смог преодолеть нежелание персонажа делиться информацией, и поэтому целевая улика не открывается.  
В сценарии порог обнаружения задаётся таким образом, чтобы наиболее важные для следствия улики имели большие значения порогов. Возможность указания дробных значений позволяет «тонко» упорядочить улики.

Для уменьшения влияния случайности нужно указывать малые значения порогов; для исключения случайности — меньше 1.

*Улика* — целевая улика персонажа, которая открывается при успешном допросе.  
Улика может быть задана сценарием преднамеренно неверно — имитация того, что персонаж лжёт / забыл.

=== Стоимость допроса, начисляемые очки

*Стоимость допроса* — ресурсная стоимость допроса любых персонажей одинакова и определяется в сценарии.  
Определяет, сколько тратится ресурса за допрос персонажа. Детектив узнаёт стоимость в начале игры.

*Очки за допрос* — базовое количество очков, которые могут быть начислены детективу за допрос персонажа.  
Для всех персонажей в сценарии определяется одинаковое базовое количество очков.  
Базовые очки начисляются за открытие целевой улики при допросе (ложной или нет).  
При начислении базовых очков дополнительно начисляется по одному очку за каждое совпадение _сущности_ в фокусе (вне зависимости от открытия улики).

[[interrogation-alg]]  
=== Алгоритм определения целевой улики в таблице допроса персонажа

Алгоритм определения целевой улики преследует следующую цель: определить улику персонажа, максимально соответствующую фокусу детектива, но при этом улики должны раскрываться начиная с наименее значимой для расследования.

В алгоритме рассматриваются строки таблицы допроса, относящиеся к выбранному персонажу.  
Из рассмотрения исключаются строки, для которых улика уже была открыта в предыдущих допросах.

1. Для каждой строки вычисляются веса фокуса EQ, EQT, NE (см. <<focus-weights-comp, вычисление весов соответствия фокусов>>).
2. Находится строка с максимальным «EQ», максимальным «EQT», минимальным «NE» и минимальным *Порогом*.
3. Если для этой строки «EQ = 0», персонаж не знает, о чём спрашивает детектив. Целевая улика не открывается.  
   Сообщается о том, что у персонажа нет нужной информации:
   * Не совпавшие ID сущностей и типы из фокуса детектива.
   * Типы сущностей не совпавших ID в табличном фокусе (как намёк на другие связи).
====
Например, для фокуса детектива «L3, P?, T?» и табличного фокуса «L4, T1, C2» будет выведено:  
«Персонаж P1 не знает о L3, P?, но намекает, что знает о L?, T?, C?».
====

[start=4]
4. Если «EQ > 0», персонаж знает, о чём спрашивает детектив.  
   Для сообщения выбираются:
   * Совпавшие ID сущностей и типы в фокусе детектива.
   * Типы сущностей не совпавших ID в табличном фокусе.

5. Если «D12 >= Порог», открывается целевая улика. Сообщается об открытии улики и связях:

====
Например, для целевой улики C8, фокуса детектива «L3, P?, C?» и табличного фокуса «L3, P7, P4, T2» будет выведено:  

«Персонаж P1 знает о L3, P?, P?, T?, связанных с C8».  
====

Сообщается, сколько очков начислено детективу.
Строка, соответствующая целевой улике, исключается из дальнейших допросов.  

Если все улики персонажа открыты, на карту персонажа выкладывается жетон «Все улики обнаружены». Дальнейшие допросы персонажа невозможны.

[start=6]   
6. Если «D12 < Порог», целевая улика не открывается. Сообщается лишь о связях:  
«Персонаж P1 знает о L3, P?, P?, T?, но не захотел делиться деталями».

== Лабораторная экспертиза

В случае необходимости подтверждения гипотезы детективы могут заказать проведение лабораторной экспертизы для проверки существования связи между *открытыми* сущностями, у которых, возможно, нет прямых отсылок друг на друга.  
Например, определить, соответствует ли пепел, найденный в локации, сигаретам, найденным у персонажа.

При проведении экспертизы существуют случайные факторы, которые влияют на её результат.  
Это влияние моделируется броском D12.

Экспертиза стоит определённого ресурса. За экспертизу детективу могут быть начислены очки.

Сценарий задаёт таблицу связей *«Лабораторная экспертиза»*, которая определяет связь между сущностями.

Процедура проведения экспертизы:

1. Детектив указывает фокус детектива — набор ID любых *открытых* сущностей или любых типов, например C1, P?.
2. Бросает дайс D12 для моделирования влияния случайных факторов.
3. По таблице «Экспертиза сущностей» определяется результат экспертизы.  
   Эта таблица доступна только через мастер-программу.
4. По завершении экспертизы заполняется карточка «Экспертное заключение», в которой указываются результаты экспертизы.

=== Таблица связей «Лабораторная экспертиза»

|===
|Фокус          |Порог|Улика
| P2, L3, L5, T6|10.0 | C2
| P3, С3, С4    |7.1  | С4
|===

*Фокус* — табличный фокус экспертизы (то же, что и <<search-focus, табличный фокус обыска>>).

На фокус детектива налагается ограничение:  
*Среди элементов фокуса детектива обязательно должны быть как минимум два ID сущностей.*

*Порог* — порог влияния случайных факторов на экспертизу.  
_Действительное_ число, которое сравнивается с выпавшим на дайсе D12.  
Если выпало меньше числа «Порога», считается, что негативное влияние факторов существенное, экспертиза проведена некачественно и целевая улика не открывается.  
В сценарии порог влияния задаётся таким образом, чтобы наиболее важные для следствия улики имели большие значения порогов. Возможность указания дробных значений позволяет «тонко» упорядочить улики.

Для уменьшения влияния случайности нужно указывать малые значения порогов; для исключения случайности — меньше 1.

*Улика* — целевая улика, по сути — лабораторное заключение, детализирующее связь.  
Например: «Обнаруженные отпечатки пальцев совпадают».

=== Стоимость экспертизы, начисляемые очки

*Стоимость экспертизы* — ресурсная стоимость любой экспертизы одинакова и определяется в сценарии.  
Определяет, сколько тратится ресурса за проведение экспертизы. Детектив узнаёт стоимость в начале игры.

*Очки за экспертизу* — базовое количество очков, которые могут быть начислены детективу за экспертизу.  
Для всех экспертиз в сценарии определяется одинаковое базовое количество очков.  
Базовые очки начисляются детективу за открытие улики.  
При начислении базовых очков дополнительно начисляется по одному очку за каждое совпадение _сущности_ в фокусе (вне зависимости от открытия улики).

== Алгоритм выявления строки связи в таблице экспертизы

Алгоритм определения связи преследует следующую цель: определить наличие связи и дополнительных данных для сущностей, максимально соответствующих фокусу детектива и броску D12.

Из рассмотрения исключаются строки, для которых в предыдущих экспертизах была открыта целевая улика.

[[expertise-quality]]  
1. Для каждой строки вычисляются веса фокуса EQ, EQT, NE (см. <<focus-weights-comp, вычисление весов соответствия фокусов>>).
2. Находится строка с максимальным «EQ», максимальным «EQT», минимальным «NE», минимальным «Порогом».
3. Если «EQ = 0», связи не выявлены. Целевая улика не открывается.  
Сообщается о невыявлении связи:
   * Не совпавшие ID сущностей и типы из фокуса детектива.
   * Типы сущностей не совпавших ID в табличном фокусе (как рекомендуемые).
====
Например: «Связь между L2, P4, C? не выявлена. Рекомендуется экспертиза L?, P?, T?».
====

[start=4]
4. Если «EQ = 1», выявлены связи для одной сущности. Целевая улика не открывается. Сообщается о связях «в общем»:
   * Совпавшие ID сущностей в фокусе детектива.
   * Типы сущностей в табличном фокусе, кроме совпавших с ID из фокуса детектива.

====
Например, для фокуса детектива «L2, L3, P?» и табличного «L2, L4, P1, T3»:  

«Выявлена связь L2 с L?, P?, T?».
====

[start=5]
5. Если «EQ > 1», связь обнаружена.  
Для сообщения подготавливаются:

   * Совпавшие ID сущностей в фокусе детектива.
   * Типы сущностей в табличном фокусе, кроме совпавших с ID из фокуса детектива.

[start=6]
 6. Если «D12 >= Порог», влияние факторов низкое, целевая улика открывается.  

====
Сообщение об обнаружении связи и открытии улики (заключении экспертизы):  
   «Обнаружена связь L2, P4 с L?, T?, P?. Заключение экспертизы С3».  
   Сообщается, сколько очков начислено детективу.
====

Строка с открытой уликой исключается из дальнейших экспертиз.  

Если для всех строк таблицы экспертизы целевые улики открыты, выкладывается жетон «Лаборатория закрыта». Дальнейшее проведение экспертиз невозможно.

[start=7]
7. Если D12 < Порог, влияние факторов высокое, целевая улика не открывается.  

====   
Сообщается: «Обнаружена связь L2, P4 с L?, T?, P?. Проведение экспертизы было затруднено».

====

[[focus-stat-hint]]  
== Статистики фокуса

Получение статистики табличных фокусов является опциональной механикой; возможность использования регулируется в сценарии.  
Получение статистики может быть разрешено для уменьшения сложности игры для новичков.

Получение статистики фокуса может быть как бесплатным, так и стоить определённого ресурса (обозначается в сценарии).

Статистика вычисляется на момент её запроса — в учёт не берутся строки, для которых уже открыты целевые улики.

[[location-glue-hint]]  
=== Статистика локации

Перед проведением обыска детектив может запросить текущую статистику локации:

1. Вычисляется процент каждого из типов сущностей во всех табличных фокусах локации.
2. Выдаётся статистика: «Возможные связи локации с P 45%, L 30%, T 25%, C 0%».

[[personage-glue-hint]]  
=== Статистика персонажа

Перед проведением допроса детектив может запросить текущую статистику персонажа:

1. Вычисляется процент каждого из типов сущностей во всех табличных фокусах персонажа.
2. Выдаётся статистика: «Персонаж может знать о P 45%, L 30%, T 25%, C 0%».

[[expertise-glue-hint]]  
=== Статистика лаборатории

Перед проведением экспертизы детектив может запросить текущую статистику лаборатории:

1. Вычисляется процент каждого из типов сущностей во всех табличных фокусах экспертизы.
2. Выдаётся статистика: «Лаборатория может определить связи между P 45%, L 30%, T 25%, C 0%».

== Прямые связи сущностей

Прямая связь между любыми сущностями возможна через упоминание в улике, а также в таблице «Экспертиза сущностей».  
Также связи задаются согласно таблице:

|===
| |Локация |Время |Улика |Персонаж

|*Локация* |Переходы между локациями| Улика |Обнаружение улики в локации| Улика
|*Время* | * |Соседние такты|Улика|Улика
|*Улика* | *  | *  |Улика| Обнаружение улики у персонажа
|*Персонаж* | * | *  | *  |Улика
|===

== Ответы

Раздел «Ответы» описывается в сценарии и раскрывается в конце игры.  
Раздел состоит из нескольких подразделов, каждый из которых раскрывает определённые аспекты преступления.  
Часть ответов содержится в описании других сущностей, например, какие из локаций и проходов скрытые, ложность улик, журналы событий, важность для расследования улик и т.п.

=== Описание преступления

Словами кратко описывается ход преступления, задействованные локации, персонажи, улики.

=== Рекомендуемая стратегия расследования

Рекомендуемая последовательность обыска, допроса, экспертизы. Какие улики использовать, какие ожидать.

== Сценраий

Сценарий задается в виде zip архива определенной структуры.
Основным файлом внути zip архива является script.yaml - документ сценария определенного формата, описывающий собственно сценарий.

<<script-template-ru.adoc, См. файл script-template.adoc>>

== Руководство по созданию сценария

<<script-guide-ru.adoc, См. файл script-guide-ru.adoc>>
