= Zacepco - Механика детективной игры

© 2026 V. Larionov. Лицензия CC BY 4.0

== О документе

Документ описывает механику детективной игры, задает общие правила по которым  она должна строится.
Для целостности игры неотъемлемым дополнением к этой механике являются *сценарии преступления*, которые описывают
сюжетную составляющую. Сама механика по сути является *фреймворком* дедуктивной детективной
игры с элементами случайности.

== Сценарий преступления

Сценарий, в рамках механики, описывает преступление, которое уже произошло. В процессе игры игроки (детективы)
должны раскрыть это преступление. Сценарий ориентируется на разную степень сложности раскрытия преступления,
описывая, например,  одно преступление или сразу несколько, с участием одного или нескольких преступников,
с наличием или отсутствием сообщников, с разным количеством подозеваемых, длительностю преступления,
размером “театра действия” т.п.

Любой сценарий содержит:

* Инструкции для подготовки к началу расследования.
* Информацию для хода расследования.
* Раздел “Ответы”, который можно посмотреть в конце игры.

Готовые сценарии идут с игрой, либо же генерируются специальной
программой.

Игра происходит по выбраному игроками сценарию и делится на две *фазы*.

В первой фазе игроки, согласно сценария, выполняют подготовительные
действия для начала расследования - сборка игрового поля и др.

Вторая фаза - расследование, кооперативный процесс раскрытия
преступления детективами.

В конце игры выводы следствия сравниваются с разделом “Ответы” сценария.

== Мастер программа

Для модерации процеса игры используется компьютерная программа - *"Мастер-программа"*
которая настраивается сценарием под конкретню игру.

== Игровые сущности и связи

Сценарий оперирует следующими типами *игровых сущностей*:

* *Персонаж (P)* - действующее лицо в преступлении;
* *Локация (L)* - часть места преступления;
* *Улика (C)* - часть информации о преступлении;
* *Время (T)* - момент времени в течении преступления;

Сами игровые сущности (кроме времени) представлены карточками сущностей.
Каждая такая карточка, в зависимости от типа сущности имеет свой формат.
Сущность идентифицируется уникальным  идентификатором, например P2, L5, C55.
Время - не имеет собственных карт, порядковый только номер  (T1,T2 ...).

Каждая из игровых сущностей может быть связана сценарием с любыми
другими сущностями. С точки зрения связи, когда одна сущность ссылается
на другую, первая называется *ключевой сущностью*, а вторая - *целевой
сущностью*.

Сценарий задает совокупность игровых сущностей и их связей, что по сути
описывает преступление. (Определяет модель преступления).

Часть из этих сущностей и связей могут не относится к преступлению и
служат для усложнения процесса расследования.

Перед началом расследования детективам известна некоторая небольшая
часть сущностей и их связей. В процессе расследования детективы
постепенно открывают остальные карты сущностей и связи.

== Открытие сущностей и связей

В игре используется механика *поэтапного* открытия детективами карт
сущностей и обнаружения связей между ними.

Детективы на основе некоторых уже открытых ключевых сущностей могут узнать
их связи с другими целевыми сущностями, как открытыми, так еще и не
открытыми. Потом отобрать другие ключевые сущности и по ним опять
определить очередные целевые сущности и связи, и так далее.

Связи сущностей, в зависимости от конкретной игровой механики
описываются сценарием в виде *таблиц связей* определенного формата.

При получении информации из таблиц связей, чтобы не раскрыть перед
детективами сразу всю информацию о преступлении, используется
*мастер-программа*.

== Элемент случайности

Дайс D12

== Ресурс, очки

В игре каждое действие детектива стоит определенного *ресурса*. В случае
успешности действия игроку начисляются *очки*. Сценарий определяет общий
*бюджет* ресурса на расследование. При исчерпании бюджета расследование
завершается _неудачно_.

Индивидуальное кол-во заработанных очков определяет лучшего детектива в
расследовании.

== Игровое время

Сценарий преступления охватывает какой-то промежуток времени. Время в
этом промежутке течет дискретно, *тактами*, с первого до последнего.
Преступление длится заданное в сценарии число тактов. Чем больше тактов,
тем сложнее раскрыть преступление. Все события в преступлении
привязываются к тактам. В каждый такт времени происходит
то-то. Считается что между тактами ничего не происходит.

== Место преступления, локации, проходы

В сценарии место преступления определяется в виде графа. В фазе подготовки к
расследованию игроки на основе этого графа из отдельных *локаций* (узлы
графа) собирают место преступления.

Каждая локация представлена картой бланка локации. На бланке напечатан только id локации
и предусмотрено место для дополнительной информации по локации, которую определяет сценарий:

* Название локации
* Описание локации
* Изображение локации

Перед началом игры из сценария распечатываются "дополнения" с информацией по локациям, вырезаются
и раскалдываются на соответствующие бланки локаций.

Локации соединяются между собой *проходами* для персонажа (карты проходов).
Проход может состоять из нескольких карт прохода (сегментов) с разной
конфигурацией прохода (прямой, поворот). Проход всегда соединяет только
две локации. В проходах никогда ничего не происходит, они лишь служат
для указания возможности перемещения персонажей между локациями.

Сценарий также может предполагать наличие *“скрытых” проходов* между
локациями, которые не обозначаются в фазе подготовки к расследованию. О
существовании таких проходов детективы узнают в процессе расследования.
При открытии в какой-то локации *улики скрытого прохода* определяется
id  целевой локации в которую ведет проход. На поле выкладывается
карта прохода соединяя локацию в которой была открыта улика скрытого прохода и целевой
локацией.

Скрытый проход может вести в *скрытую локацию*. Это такая локация, о
которой детективы не знают до начала расследования. В качестве скрытой
локации может выступать любая из локаций, еще не включенная в игровое
поле. Обнаруженная скрытая локация выкладывается на игровое поле рядом с
той локацией где была обнаружена улика скрытого прохода. Локация
соединяется картой прохода с той локацией где была обнаружена улика
скрытого прохода. После открытия локации она становится доступной для следсвтвенных
действий.

Информация о всех скрытых проходах и локациях явно указывается в разделе
*ответы* сценария.

При разработке сценария локации должн определятся таким образом чтобы
учитывался их смысл в расследовании. Например в пещере может не быть света,
в подвал персонаж может войти только с
ключем, в оранжерее может расти ядовитое растение, бар работает с 3-го
до 6-го такта и др. Смысловая нагрузка, описание локации должна помогать
детективам в расследовании.

== Персонажи

Действующее лицо в преступлении - это *персонаж*. Набор
персонажей в игре определяется сценарием. Сценарий задает явных
персонажей - они известны перед началом расследования. Их карты
выкладываются рядом с игровым полем.

Сценарий может также подразумевать, наличие *скрытых персонажей*. Скрытый
персонаж - один из тех, чья карта еще не выложена из колоды персонажей в
открытую на стол. Определить наличие скрытого персонажа можно в процессе
расследования, логически, на основе обнаруженных улик. Либо же,
при открытии улики  с прямой ссылкой на этого скрытого
персонажа. При обнаружении улики с сылкой на скрытого персонажа его карта из
колоды персонажей выкладывается в открытую рядом с игровым полем к
картам остальных персонажей. После этого персонаж становится доступным для следственных действий.
В сценарии, в разделе “Ответы”, перечислены все скрытые персонажи.

Персонаж представлен картой бланка персонажа. Карта бланка имеет определенный цвет, на ней
напечатан id персонажа и предусмотрено место для дополнительной информации о персонаже, которую определяет
сценарий:

* Имя перонажа
* Досье персонажа
* Изображение пероснажа

Перед началом игры из сценария распечатываются "дополнения" с информацией о персонаже, вырезаются
и раскалдываются на соответствующие бланки персонажей.

Песонажи в сценарии должны описываться таким образом,
чтобы это поисание помогло детективам в расследовании.

== Движения и действия персонажа

У каждого персонажа во время преступления *в каждый такт* времени есть
только следующие *альтернативные* возможности:

* Перейти в соседнюю локацию и ничего не делать.
* Перейти в соседнюю локацию и выполнить какое либо действие.
* Остаться в локации и выполнить какое либо действие.

Перемещение происходит в смежную локацию при наличие прохода.
Со стороны сценария  возможны какие-либо  ограничения на проход, например
дверь, которую нужно открыть ключем.
В общем случае персонаж может посещать одну и ту же локацию несколько раз в разных
тактах. Для более легких вариантов игры - персонаж может посетить
локацию только один раз.

Путь движения персонажа (последовательность локаций) подразумевается
сценарием, но игрокам явно не раскрывается. Игроки могут определить
этот путь при расследовании.

Пути персонажей раскрываются сценарием в разделе “Ответы” - для каждого
персонажа обозначены его перемещения в виде последовательности id
локаций для каждого такта. Эту информацию можно посмотреть в конце игры.

Во время фазы расследования, для визуализации пути (*трека*) движения
персонажа по игровому полю в локации выкладываются жетоны цвета
персонажа. На каждом жетоне номер такта в котором персонаж находился в
локации на которой лежит жетон. Такие жетоны называются жетоны трека
персонажа.


При нахождении в локации персонаж может выполнить какое либо одно действие.
Само действие как сущность механика не предусматривает, но результатом этого действия
становится  *улика*, которая остается либо в локаци, либо у персонажа который совершил
дейсвтвие либо над которым совершено действие.

== Улики

*Улика* - часть сведений о совершенном преступлении, которые
последовательно обнаруживают детективы при расследовании.
Уликой может быть какой-либо физический предмет, событие, какая-то информация, факт.

Примеры улик: свидетельское показание, мотив, записка, окурок
сигареты, привычка, пристрастие персонажа к курению, факт отсутствия предмета в
локации.

Сценарий преступления определяет набор улик, участвующих в игре.
Улика представлена картой бланка улики с напечатанным на ней id
и предусмотрено место для дополнительной информации об улике , которую определяет сценарий:

* Краткое название улики
* Описание улики
* Изображение улики

Перед началом игры из сценария распечатываются "дополнения" с информацией об локаах, вырезаются
и раскалдываются на соответствующие бланки улик.

Некоторые из улик могут не иметь отношения к преступлению и служат
для того чтобы усложнить игру. Чем больше таких улик тем сложнее
игра.

Изначально улики скрыты от детективов. В процессе расследования
детективы постепенно “открывают” улики - выкладывают в открытую карты
улик.

Если в открытой улике есть ссылки на другие улики, эти улики
также открываются (рекурсивно). Сценарий не должен определять глубокую
рекурсию открываемых улик.

Примеры улик:

* Улика C1 : “Показания. Видел персонажа P1 (Горничная)  во время 4-го така в локации L2 (Столовая)”
* Улика C2 : “В этой локации обнаружен скрытый проход в локацию L4 (Подвал)."
* Улика C6 : “В этой локации отсутствует С2 (Подсвешник) но изначально было тут”
* Улика C12 : “Сломанные часы. Стрелка показывает T8 тактов”
* Улика C13 : “В этой локации был замечен персонаж P1 (Садовник) в T3 тактов с C6 (Нож) в руке”.

== Обыск локации

При проведении расследования детективы могут *“обыскать”* любую открытую локацию (в
том числе и ранее скрытую) чтобы попытаться открыть улики, связанные
с этой локацией. В результате обыска с некоторой вероятностью может быть
"обнаружена" (открыта) улика.

Сценарий задает таблица связей *“Обыск локаций”* которая определяет связь
между локациями и уликами. При обыске используется механика
вероятностного обнаружения улики вместе с механикой *“Фокус обыска”*,
которая позволяет с большей вероятностью обнаружить улику на которую
направлен фокус обыска и получить больше очков.

Попытка обыска стоит ресурса. Для каждой локации своя стоимость. За
успешный обыск детективу начисляются очки.

Процедура обыска:

. Детектив заявляют о проведении обыска в конкретной локации.
. Опционально указывает фокус обыска - набор id любых *открытых* сущностей
. Кидает дайс D12 .
. По таблице “Обыск локаций” определяют какую улику
следует открыть. Доступ к таблице обыска осуществляется через мастер-программу.

Таблица “Обыск локаций” имеет следующий формат:

|===
|Локация |Стоимость|Фокус           |Порог|Улика|Очки

| L1     | 3       | P4, L3, L4, T4 |5.2  |С8   | 1
|  *     | *       | L4, С5, С6     |5.0  |С3   | 3
| L5     | 4       |    -           |8.0  |С12  | 2
|===

*Локация* - id обыскиваемой локации.

*Стоимость* - ресурсная стоимость обыска. Сколько ресурсов тратится
за обыск в локации. Стоимость озвучивается детективу до
обыска, если это дорого - он может отказаться от обыска, при этом ресурс не тратится.

*Фокус* -  фокус обыска служит для повышения вероятности открытия улик, имеющих связи
с интересующими детектива целевыми сущностями.
В ячейках фокуса перечисляются id сущностей связаных с уликой.

Для фокуса обыска детктив может указать несколько *открытых* сущностей.
Их максимальное количество определяется в сценарии (обычно 3).

*Порог* -  порог обнаружения улики. _Действительное_ число, которое сравнивается с выпавшим на дайсе D12.
Если выпало больше или равное числу в этой колонке -  считается что улика обнаружена.
В сценарии порог обнаружения задается таким образом, чтобы наиболее
важные для следствия улики имели большие значения порогов.
Дествительное число дает возможность "тонко" упорядочить
сущности.

*Улика* - id открываемой улики. Карта обнаруженной улики  выкладывается в
открытую, на локацию выкладывается жетон с id откртой улики.

Если все улики локации открыты, на локацию выкладывается жетон “Все улики обнаружены”.

*Очки* - количество очков для начисления  детективу за обыск.
Очки начисляются только если _НЕ_ произошло *<<accidental-discovery,случайное обнаружение>>* улики.
Если использовался фокус обыска, дополнительно начисляется по одному очку за каждую совпавшую сущность в фокусе.

== Алгоритм определения целевой улики в таблице обыска локации

Цель алгоритма: определить улику, наиболее соответствующю фокусу обыска и броску D12.

В алгоритме рассматриваются строки таблицы обыска, относящиеся к выбранной локации. Из рассмотрения
исключаются строки, для которых улика уже была открыта в предыдущих обысках.

1) Выполняется упорядочивание строк в соответствии с наличием или отсутствием фокуса обыска:

* Без фокуса обыска - Строки упорядочиваются по убыванию порога обнаружения.
* С фокусом обыска - для каждой строки вычисляется значение N = [количеств совпавших сущностей] и
M = [количество *НЕ* совпавших сущностей] в фокусе обыска детектива и табличном фокусе.
Строки упорядочиваются по убыванию N, возрастанию M, убыванию "Порога".

2)  Последовательно, начиная с первой строки, идет сравнение "Порога" с числом на дайсе D12.

3)  Если значение D12 >= "Порог" - просмотр останавливается, считается что улика обнаружена.
Сообщается id улики. Если был задействован фокус - сообщается какие именно сущности в фокусе совпали,
сколько сущностей не совпало в табличном фокусе.

[[accidental-discovery]]
4) Если подходящей строки не найдено, происходит *"Случайное обнаружение"* улики: в локации открывается улика
с самым низким порогом. Считается что детектив нашел что-то подозрительное. При этом сообщается что было
случайное обнаружение.


[[interrogation]]
== Допрос персонажа

Сценарий с каждым из персонажей связывает некоторые улики.
Считается, что часть из них была у персонажа до
преступления. Например - одежда, личные вещи, характер. Часть они получили во время
преступления - подобрали в локациях или получили от других персонажей.
Например нож, записка. Часть улик персонажа описывают их
неотъемлемые черты. Например привычки, пристрастие к алкоголю, характер
и т.п. Остальная часть улик - свидетельские показания персонажа.
Сценарий также предполагает, что в процессе преступления персонажи могут
оставлять улики в локациях, передавать или подкидывать другим персонажам
при встрече с ними в одной локации.

Часть улик персонажа может быть  известна детективам (например одежда
и т.п.) до расследования. Другая часть улик - скрыта.
Аналогично процедуре обыска локации, для открытия таких
улик, связанных с персонажем детектив может *“допросить”* любого открытого
персонажа (в том числе и ранее скрытого). В результате допроса может
быть открыта очередная улика персонажа и установлена связь с другими уликами.

Во время допроса детектив “спрашивает” персонажа об одной или нескольких известных детективу ключевых
сущностях - т.е. определяет *фокус допроса*. Если персонажу “известно” о
них (о всех или о части), открывается связанная с этими сущностями улика. Механика  допроса построена таким образом,
чтобы детективу, без знания ключевых улик было бы затруднительно открыть какую либо целевую улику персонажа.

При ответе персонаж может *“сказать неправду”* - открывается улика
которая на самом деле никак не связана с ключевыми сущностями в фокусе допроса. Сценарий
регулируют кол-во “ложных” улик.

Допрос персонажа стоит ресурса. Для каждого персонажа указывается своя
стоимость. Если детктиву при допросе удалось открыть улику ему
начисляется очки пропорционально количеству сущностей в фокусе допроса детектива.

Процедура допроса:

. Детектив выбирает персонажа которого будет допрашивать
. Указывает фокус допроса - набор id любых *открытых* сущностей
. По таблице допроса определяется какую улику следует открыть. Доступ к таблице допроса
осуществляется через мастер-программу.

Для допроса персонажа используется таблица связей “Допрос персонажа”:

|===
|Персонаж |Стоимость |Фокус             |Важность| Улика |Очки

|P1       |3         |P2, L3, C4, С5, T2|   1.0  |C3     |2
|P4       |4         |C4, T5, T6        |   1.0  |C12    |3
| *       | *        |P5                |   1.2  |C15    |5
|===

*Персонаж* - допрашиваемый персонаж. Детектив на основе известных ему из хода
расследования улик и логических заключений выбирает персонажа которого
нужно допросить.

*Стоимость* -  стоимость допроса персонажа. Сколько тратится ресурса за попытку
допроса. Стоимость озвучивается детективу до попытки допроса. После того как
детектив узнает стоимость, он может отказаться от допроса, при этом ресурс не тратится.

*Фокус* - фокус допроса служит для определения улики которую следует открыть.  В ячейках фокуса перечисляются
id сущностей, связанных с уликой. Можно через запятую перечислить несколько id  - это
трактуется как любая из них.

Для фокуса допроса детктив может указать несколько любых *открытых* сущностей.
Их максимальное количество определяется в сценарии (обычно 3).

*Важность*  - важность улики для расследования. _Действительное_ число задающее степень важности
(чем больше, тем важнее). Само значение не важно, важен лиш их порядок следования. Возможность
указывать дробные значения нужна для гибкости указания порядка.

*Улика*  -  целевая улика персонажа, который открывается при успешном допросе. Улика может
быть задана сценарием преднамеренно не верно - имитация того, что персонаж лжет/забыл.

Если все улики персонажа открыты, на карту ерсонажа выкладывается жетон “Все улики обнаружены”.

*Очки* - количество очков для начисления  детективу при успешном допросе.
Дополнительно начисляется по одному очку за каждую совпавшую сущность в фокусе.

[[targetartalg]]
=== Алгоритм определения целевой улики в таблице допроса персонажа

Алгоритм определения целевой улики преследует следующую цель:
определить улику персонажа максимально соответствующую фокусу детектива, но при этом
улики должны раскрываться начиная с наименее значимой для расследования.

В алгоритме рассматриваются строки таблицы допроса, относящиеся к выбранному персонажу. Из рассмотрения
исключаются строки, для которых улика уже была открыта в предыдущих допросах.

. Для каждой строки вычисляется значение
N = [количество совпавших] и
M = [количество *НЕ* совпавших]
сущностей в фокусе допроса детектива и табличном фокусе.
. Находится строка с максимальным N, минимальным M и минимальной *Важностью*.
. Если для этой строки N = 0 то обьявляется, что допрос не успешен. Никакая улика не открывается.
При этом дается <<personage-glue-hint, подсказка о типах еще не раскрытых улик персонажа>>.
. Если N > 0 то допрос успешен - открывается соответсвующая улика, и сообщаяется какие именно сущности в
фокусе допроса совпали и сколько не совпало в табличном фокусе.

[[personage-glue-hint]]
=== Подсказка о типах нераскрытых улик у персонажа

. Для каждого типа сущности  (P, L, C, T) подсчитывается сколько сущностей каждого типа есть у персонажа
в фокусе допроса для еше не открытых улик.
. Подсчитывается процент для каждого типа относительно общего числа и выдаетс эта информация.
Например: "Персонаж заявил что он кое что знает о Персонажах (30%), Локациях (25%), Уликах (25%), Времени (20%)"

== Лабораторная экспертиза

В случае необходимости подтверждения гипотезы детективы могут заказать
проведение лабораторной экспертизы для проверки существования связи между *открытми*
сущностями, у которых возможно нет прямых отсылок друг на друга.
Например определить, соответствует ли пепел найденный в
локации сигаретам найденным у персонажа.

Проведение экспертизы стоит определенного ресурса. Величина ресурса для
любой экспертизы постоянна, указывается в сценарии. За успешно найденную связь детективу
начисляется очки.

Ограничений на количество экспертиз нет, можно проводить экспертизу с одними и темиже сущностями
несколько раз.

Процедура проведения экспертизы:

. Детектив указывае две и более *открытых* сущности для фокуса экспертизы.
. Бросает дайс D12.
. По таблице “Экспертиза сущностей” определяется выявлена ли связь между указаными
сущностями или нет, дополнительные данные по экспертизе.
Эта таблица доступна только через мастер-программу.
. По завершению экспертизы заполняется карточка “Экспертное заключение”
где указывается id  исследуемых сущностей, результат экспертизы -
установлена связь или нет, факт наличия других связей.

Пример таблицы “Лабораторная экспертиза ”:

|===
|Фокус          |Порог|Очки
| P2, L3, L5, T6|10.0 |3
| P3, С3, С4    |7.1  |4
|===

*Фокус* - id сущностей подлежащих экспертизе. В ячейках фокуса перечисляются
id сущностей, между которыми есть связь.

Для фокуса экспертизы детктив может указать от двух любых *открытых* сущностей.
Их максимальное количество определяется в сценарии (обычно 3).

*Порог* -  порог моделирования *"качества"* экспертизы. _Действительное_ число, которое сравнивается
с выпавшим на дайсе D12. Возможность указыать не целые значения позволяет "тонко" упорядочить
сущности по порогу.

*Очки* - количество очков начисляемых детективу за успешное выявление связей.
Дополнительно начисляется по одному очку за каждое совпадение в фокусе экспертизы

== Алгоритм выявления строки связи в таблице экспертиза

. Для каждой строки вычисляется значение N = [количество совпавших] и M = [количество *НЕ* совпавших]
сущностей в фокусе допроса детектива и табличном фокусе.
. Находится строка с максимальным N и минимальным M, максимальным Порогом
. Если N < 2 - экспертиза не выявила связей. Обьявляется : "Связь не выявлена"
. Если N > 1 - связь обнаружена. Объявляется: "Связь обнаружена".
. Если N > 0 - моделируется качество экспертизы:
Если значение D12 >= "Порог", - считается что экспертиза была качественная и в дополнении
 сообщается какие именно сущности в фокусе совпали, сколько  в табличном фокусе не совпало.
Например: "Признаки связи L1, P3 и еще N сущностей."

== Прямые связи сущностей

Прямая связь между любыми сущностями возможна через упоминание в улики а также
в таблице Экспертиза сущностей. Также связи затаюся согласно таблице:
|===
| |Локация |Время |Улика |Персонаж

|Локация |Переходы между локациями| |Обнаружение улики в локации|
|Время | |Соседние такты||
|Улика | | || Обнаружение улики у персонажа
|Персонаж | | | |
|===

== Шаблон сценария
<<script-template-ru.adoc, См. файл script-template.adoc>>

== Руководство по созданию сценария
<<script-guide-ru.adoc, См. файл script-guide-ru.adoc>>