= Zacepco - Механика детективной игры

© 2026 V. Larionov.
Лицензия CC BY 4.0

== О документе

Документ описывает механику детективной игры, задает общие правила по которым она должна строится.
Для целостности игры неотъемлемым дополнением к этой механике являются *сценарии преступления*, которые описывают
сюжетную составляющую.
Сама механика по сути является *фреймворком* дедуктивной детективной игры с элементами случайности.

== Сценарий преступления

Сценарий, в рамках механики, описывает преступление, которое уже произошло.
В процессе игры игроки (детективы) должны раскрыть это преступление.
Сценарий ориентируется на разную степень сложности раскрытия преступления, описывая, например, одно преступление или
сразу несколько, с участием одного или нескольких преступников, с наличием или отсутствием сообщников, с разным
количеством подозеваемых, длительностю преступления, размером “театра действия” т.п.

Любой сценарий содержит:

* Инструкции для подготовки к началу расследования.
* Информацию для хода расследования.
* Раздел “Ответы”, который можно посмотреть в конце игры.

Готовые сценарии идут с игрой, либо же генерируются специальной программой.

Игра происходит по выбраному игроками сценарию и делится на две *фазы*.

В первой фазе игроки, согласно сценария, выполняют подготовительные действия для начала расследования - сборка игрового
поля и др.

Вторая фаза - расследование, кооперативный процесс раскрытия преступления детективами.

В конце игры выводы следствия сравниваются с разделом “Ответы” сценария.

== Мастер программа

Для модерации процеса игры используется компьютерная программа - *"Мастер-программа"*
которая настраивается сценарием под конкретню игру.
Программа также автоматизирует все расчеты связанные с игровым процессом и контролирует игровые механики.

== Игровые сущности и связи

Сценарий оперирует следующими типами *игровых сущностей*:

* *Персонаж (P)* - действующее лицо в преступлении;
* *Локация (L)* - часть места преступления;
* *Улика (C)* - часть информации о преступлении;
* *Время (T)* - момент времени в течении преступления;

Сами игровые сущности (кроме времени) представлены карточками сущностей.
Каждая такая карточка, в зависимости от типа сущности имеет свой формат.
Сущность идентифицируется уникальным идентификатором, например P2, L5, C55.
Время - не имеет собственных карт, порядковый только номер (T1,T2 ...).

Каждая из игровых сущностей может быть связана сценарием с любыми другими сущностями.
С точки зрения связи, когда одна сущность ссылается на другую, первая называется *ключевой сущностью*,
а вторая - *целевой сущностью*.

Сценарий задает совокупность игровых сущностей и их связей, что по сути описывает преступление.
(Определяет модель преступления).

Часть из этих сущностей и связей могут не относится к преступлению и служат для усложнения процесса расследования.

Перед началом расследования детективам известна некоторая небольшая часть сущностей и их связей.
В процессе расследования детективы постепенно открывают остальные карты сущностей и связи.

== Открытие сущностей и связей

В игре используется механика *поэтапного* открытия детективами карт сущностей и обнаружения связей между ними.

Детективы на основе некоторых уже открытых ключевых сущностей могут узнать их связи с другими целевыми сущностями, как
открытыми, так еще и не открытыми.
Потом отобрать другие ключевые сущности и по ним опять определить очередные целевые сущности и связи, и так далее.

Связи сущностей, в зависимости от конкретной игровой механики описываются сценарием в виде *таблиц связей* определенного
формата.

При получении информации из таблиц связей, чтобы не раскрыть перед детективами сразу всю информацию о преступлении,
используется
*мастер-программа*.

== Элемент случайности

Дайс D12

== Ресурс, очки

В игре каждое действие детектива стоит определенного *ресурса*.
В случае успешности действия игроку начисляются *очки*.
Сценарий определяет общий
*бюджет* ресурса на расследование.
При исчерпании бюджета расследование останавливается, детективы должы сдеать выводы по имеющимся данным и сравнить
результаты с ответами.

Индивидуальное кол-во заработанных очков определяет лучшего детектива в расследовании.

== Игровое время

Сценарий преступления охватывает какой-то промежуток времени.
Время в этом промежутке течет дискретно, *тактами*, с первого до последнего.
Преступление длится заданное в сценарии число тактов.
Чем больше тактов, тем сложнее раскрыть преступление.
Все события в преступлении привязываются к тактам.
В каждый такт времени происходит то-то.
Считается что между тактами ничего не происходит.

== Место преступления, локации, проходы

В сценарии место преступления определяется в виде графа.
В фазе подготовки к расследованию игроки на основе этого графа из отдельных *локаций* (узлы графа) собирают место
преступления.

Каждая локация представлена картой бланка локации.
На бланке напечатан только id локации и предусмотрено место для дополнительной информации по локации, которую определяет
сценарий:

* Название локации
* Описание локации
* Изображение локации

Перед началом игры из сценария распечатываются "дополнения" с информацией по локациям, вырезаются и раскалдываются на
соответствующие бланки локаций.

Локации соединяются между собой *проходами* для персонажа (карты проходов).
Проход может состоять из нескольких карт прохода (сегментов) с разной конфигурацией прохода (прямой, поворот).
Проход всегда соединяет только две локации.
В проходах никогда ничего не происходит, они лишь служат для указания возможности перемещения персонажей между локациями.

Сценарий также может предполагать наличие *“скрытых” проходов* между локациями, которые не обозначаются в фазе подготовки
к расследованию.
О существовании таких проходов детективы узнают в процессе расследования.
При открытии в какой-то локации *улики скрытого прохода* определяется id целевой локации в которую ведет проход.
На поле выкладывается карта прохода соединяя локацию в которой была открыта улика скрытого прохода и целевой локацией.

Скрытый проход может вести в *скрытую локацию*.
Это такая локация, о которой детективы не знают до начала расследования.
В качестве скрытой локации может выступать любая из локаций, еще не включенная в игровое поле.
Обнаруженная скрытая локация выкладывается на игровое поле рядом с той локацией где была обнаружена улика скрытого прохода.
Локация соединяется картой прохода с той локацией где была обнаружена улика скрытого прохода.
После открытия локации она становится доступной для следсвтвенных действий.

Информация о всех скрытых проходах и локациях явно указывается в разделе
*ответы* сценария.

При разработке сценария локации должн определятся таким образом чтобы учитывался их смысл в расследовании.
Например в пещере может не быть света, в подвал персонаж может войти только с ключем, в оранжерее может расти ядовитое
растение, бар работает с 3-го до 6-го такта и др.
Смысловая нагрузка, описание локации должна помогать детективам в расследовании.

== Персонажи

Действующее лицо в преступлении - это *персонаж*.
Набор персонажей в игре определяется сценарием.
Сценарий задает явных персонажей - они известны перед началом расследования.
Их карты выкладываются рядом с игровым полем.

Сценарий может также подразумевать, наличие *скрытых персонажей*.
Скрытый персонаж - один из тех, чья карта еще не выложена из колоды персонажей в открытую на стол.
Определить наличие скрытого персонажа можно в процессе расследования, логически, на основе обнаруженных улик.
Либо же, при открытии улики с прямой ссылкой на этого скрытого персонажа.
При обнаружении улики с сылкой на скрытого персонажа его карта из колоды персонажей выкладывается в открытую рядом с
игровым полем к картам остальных персонажей.
После этого персонаж становится доступным для следственных действий.
В сценарии, в разделе “Ответы”, перечислены все скрытые персонажи.

Персонаж представлен картой бланка персонажа.
Карта бланка имеет определенный цвет, на ней напечатан id персонажа и предусмотрено место для дополнительной информации
о персонаже, которую определяет сценарий:

* Имя перонажа
* Досье персонажа
* Изображение пероснажа

Перед началом игры из сценария распечатываются "дополнения" с информацией о персонаже, вырезаются и раскалдываются
на соответствующие бланки персонажей.

Песонажи в сценарии должны описываться таким образом, чтобы это поисание помогло детективам в расследовании.

== Движения и действия персонажа

У каждого персонажа во время преступления *в каждый такт* времени есть только следующие *альтернативные* возможности:

* Перейти в соседнюю локацию и ничего не делать.
* Перейти в соседнюю локацию и выполнить какое либо действие.
* Остаться в локации и выполнить какое либо действие.

Перемещение происходит в смежную локацию при наличие прохода.
Со стороны сценария возможны какие-либо ограничения на проход, например дверь, которую нужно открыть ключем.
В общем случае персонаж может посещать одну и ту же локацию несколько раз в разных тактах.
Для более легких вариантов игры - персонаж может посетить локацию только один раз.

Путь движения персонажа (последовательность локаций) подразумевается сценарием, но игрокам явно не раскрывается.
Игроки могут определить этот путь при расследовании.

Пути персонажей раскрываются сценарием в разделе “Ответы” - для каждого персонажа обозначены его перемещения в виде
последовательности id локаций для каждого такта.
Эту информацию можно посмотреть в конце игры.

Во время фазы расследования, для визуализации пути (*трека*) движения персонажа по игровому полю в локации выкладываются
жетоны цвета персонажа.
На каждом жетоне номер такта в котором персонаж находился в локации на которой лежит жетон.
Такие жетоны называются жетоны трека персонажа.

При нахождении в локации персонаж может выполнить какое либо одно действие.
Само действие как сущность механика не предусматривает, но результатом этого действия становится  *улика*, которая
остается либо в локаци, либо у персонажа который совершил дейсвтвие либо над которым совершено действие.

== Улики

*Улика* - часть сведений о совершенном преступлении, которые последовательно обнаруживают детективы при расследовании.
Уликой может быть какой-либо физический предмет, событие, какая-то информация, факт.

Примеры улик: свидетельское показание, мотив, записка, окурок сигареты, привычка, пристрастие персонажа к курению,
факт отсутствия предмета в локации, лабораторное заключение.

Сценарий преступления определяет набор улик, участвующих в игре.
Улика представлена картой бланка улики с напечатанным на ней id и предусмотрено место для дополнительной информации
об улике , которую определяет сценарий:

* Краткое название улики
* Описание улики
* Изображение улики

Перед началом игры из сценария распечатываются "дополнения" с информацией об локаах, вырезаются и раскалдываются на
соответствующие бланки улик.

Некоторые из улик могут не иметь отношения к преступлению и служат для того чтобы усложнить игру.
Чем больше таких улик тем сложнее игра.

Изначально улики скрыты от детективов.
В процессе расследования детективы постепенно “открывают” улики - выкладывают в открытую карты улик.

Если в открытой улике есть ссылки на другие улики, эти улики также открываются (рекурсивно).
Сценарий не должен определять глубокую рекурсию открываемых улик.

Примеры улик:

* Улика C1 : “Показания.
Видел персонажа P1 (Горничная) во время 4-го така в локации L2 (Столовая)”
* Улика C2 : “В этой локации обнаружен скрытый проход в локацию L4 (Подвал)."
* Улика C6 : “В этой локации отсутствует С2 (Подсвешник) но изначально было тут”
* Улика C12 : “Сломанные часы.
Стрелка показывает T8 тактов”
* Улика C13 : “В этой локации был замечен персонаж P1 (Садовник) в T3 тактов с C6 (Нож) в руке”.

== Обыск локации

При проведении расследования детективы могут *“обыскать”* любую открытую локацию (в том числе и ранее скрытую) чтобы
попытаться открыть улики, связанные с этой локацией.
В результате обыска с некоторой вероятностью может быть "обнаружена" (открыта) улика.

Сценарий задает таблицу связей *“Обыск локаций”* которая определяет связь между локациями и уликами.
При обыске используется механика вероятностного обнаружения улики вместе с механикой *“Фокус обыска”*, которая позволяет
с большей вероятностью обнаружить улику на которую направлен фокус обыска и получить больше очков.

Обыск локации стоит определенного ресурса. За обыск детективу могут быть начислены очки.

Процедура обыска:

. Детектив заявляют о проведении обыска в конкретной локации, например L1.
. Указывает фокус обыска - набор id любых *открытых* сущностей или любых типов, например: T4,L?,C?
. Кидает дайс D12 для моделирования вероятности обнаружения улики.
. По таблице “Обыск локаций” определяеся результат обыска.
Доступ к таблице обыска осуществляется через мастер-программу.

=== Таблица свзей “Обыск локаций”

|===
|Локация |Фокус           |Порог|Улика

| L1     | P4, L3, L4, T4 |5.2  |С8
|  *     | L4, С5, С6     |5.0  |С3
| L5     |     L6         |8.0  |С12
|===

*Локация* - id обыскиваемой локации.

[[search-focus]]
*Фокус* - фокус обыска. Служит для повышения вероятности открытия улик, имеющих связи с интересующими детектива целевыми
сущностями. В табличном фокусе перечисляются id сущностей связаных с целевой уликой.
Можно через запятую перечислить несколько id одинакового типа - это трактуется как любой из них.

Фокус детктива может состоять из одного или нескольких id *открытых* сущностей или любых типов сущностей.
Например: "P1,C1,T?". Максимальное количество элементов в фоксе детктива определяется в сценарии (обычно 3).

*Порог* - порог обнаружения улики. _Действительное_ число, которое сравнивается с выпавшим на дайсе D12.
Если выпало меньше "Порога" - считается что сыграли негативные факторы и целевая улика не обнаружена.
В сценарии порог обнаружения задается таким образом, чтобы наиболее важные для следствия улики имели большие значения
порогов. Возможность указания дробных значений позволяет "тонко" упорядочить улики.

Для уменьшения влияния случайности, нужно указывать малые значения порогов, для исключения случанойсти - меньше 1

*Улика* - id целевой улики персонажа. Карта обнаруженной улики выкладывается в открытую,
Для обозначения места где была найдена улика на локацию выкладывается жетон с id откртой улики.

Если все улики локации открыты, на локацию выкладывается жетон “Все улики обнаружены”.

=== Стоимость обыска, начисление очков
[[search-cost]]
*Стоимость быска* - ресурсная стоимость обыска для любых локаций одинакова и определяется в сценарии.
Определяет сколько ресурсов тратится за обыск в локации. Стоимость детектив узнает в начале игры.

[[search-points]]
*Очки за обыск* - базовое количество очков которые могут быть начислены детективу за обыск локации.
Для всех локаций в сценарии определяется одинаковое базовое количество очков.
Базовые  очки начисляются за открытие улики, но только если она
 _НЕ_ была *<<accidental-discovery,случайно обнаружена>>*.
Начисляется по одному очку за каждое совпадение _сущности_ в фокусе (вне зависимости от случайности обнаружения улики).

== Алгоритм определения целевой улики в таблице обыска локации

Цель алгоритма: определить улику, наиболее соответствующю фокусу обыска и броску D12.

В алгоритме рассматриваются строки таблицы обыска, относящиеся к выбранной локации.
Из рассмотрения исключаются строки, для которых улика уже была открыта в предыдущих обысках.

1) Для каждой строки вычисляются веса фокуса A,B,N.  См. <<focus-weights-comp, вычисление весов соответствия фокусов>>

2) Строки таблицы упорядочиваются по убыванию "A", убыванию "B", возрастнию "N", убыванию *Порога*.

3) Последовательно, начиная с первой строки, идет сравнение "Порога" с числом на дайсе D12.

4) Если значение D12 >= "Порог" - просмотр останавливается. Улика обнаружена, она открывается.

[[accidental-discovery]]
5) Если подходящей строки не найдено (значение D12 недостаточно), происходит *"Случайное обнаружение"* улики:
в локации открывается улика с самым низким порогом. Сообщается что случайно обнаружена подзительна улика.

6) Сообщается о совпадающих элементах (сущности + типы)  _фокуса детектива_  с табличным фокусом открытой улики :

* Совпавшие id сущностей и типов в фокусе детектива;
* Типы id не совпавших сущностей в табличном фокусе.

Например для фокуса детектива "P2,T4,C?" и табличного фокуса "P1,P2,T4,L2" будет выведено:
"В локации L1 была найдена улика C2 связанная с P2, T4, P?, L?".

7) Сообщается сколько очков начислено детективу.

[[focus-weights-comp]]
=== Вычисляение весов соответствия фокусов

Вычисляются следующие значения весов сооветствия фокусов детектива и табличного:
A = [количеств совпавших id сущностей в фокусах],
B = [количеств совпавших типов в фокусах],
N = [количество *НЕ* совпавших сущностей или типов ] в фокусе обыска детектива и
табличном фокусе.

Сначала вычисляется "A" путем сопастовления id в обоих фокусах. Далее исключаются совпавшие id из обоих фокусов.
Для вычисления "B" сравниваются прямо указанные в фокусе детектива типы сущностей  (P?, L?..) с типами оставшихся в табличном фокусе
id сущностей. Совпавшие при вычислении "B" элементы исключаются из обоих фокусов.
"N" вычисляется как суммарное количество оставшихся сущностей в фокусах.

Например фокус детектива P1, P2, T? в старвнении с табличным P2,T4,C1 дает:
A=1 (для P2), B=1 (для T?), N=2 (для P1, C1)

[[interrogation]]
== Допрос персонажа

Сценарий с каждым из персонажей связывает некоторые улики.
Считается, что часть из них была у персонажа до преступления.
Например - одежда, личные вещи, характер.
Часть они получили во время преступления - подобрали в локациях или получили от других персонажей.
Например нож, записка.
Часть улик персонажа описывают их неотъемлемые черты.
Например привычки, пристрастие к алкоголю, характер и т.п. Остальная часть улик - свидетельские показания персонажа.
Сценарий также предполагает, что в процессе преступления персонажи могут оставлять улики в локациях, передавать или
подкидывать другим персонажам при встрече с ними в одной локации.

Часть улик персонажа может быть известна детективам (например одежда и т.п.) до расследования.
Другая часть улик - скрыта.
Аналогично процедуре обыска локации, для открытия таких улик, связанных с персонажем детектив может *“допросить”*
любого открытого персонажа (в том числе и ранее скрытого).
В результате допроса может быть открыта очередная улика персонажа и установлена связь с другими уликами.

Во время допроса детектив “спрашивает” персонажа об известных следствию фактах (открытых ключевых сущностях)
или о гипотизах следствия  (о любых типах сущностей)  - т.е. определяет *фокус допроса*.
Если персонажу “известно” что либо об этом, открывается связанная с фокусом улика и ее связи.
Механика допроса построена таким образом, чтобы детективу, без знания ключевых сущностей или их типов было
затруднительно открыть релевантную целевую улику персонажа.

При ответе персонаж может *“сказать неправду”* - открывается улика которая на самом деле никак не связана с ключевыми
сущностями в фокусе допроса. Сценарий регулируют кол-во “ложных” улик. Ложность улики может быть установлена только
при дедуктивном анализе. В разделе "Ответы" перечисляются какие улики были действительно ложными.

Каждый персонаж в той или иной степени не желает делиться определенной информацией, а детектив использует
психологическое давление чтобы получить максимум информации. Это взаимодействие имеет случайный характер и моделируется
с помощью броска D12.

Допрос персонажа стоит определенного ресурса. За допрос детективу могут быть начислены очки.

Сценарий задает таблицу связей *“Допрос персонажа”* которая определяет связь между персонажами и уликами.

Процедура допроса:

. Детектив выбирает персонажа которого будет допрашивать, например P1.
. Указывает фокус допроса - набор id любых *открытых* сущностей или любых типов, напрмимер L1,P?
. Бросает D12 для моделированя психологического давления на персонажа.
. По таблице допроса определяется результат допроса.
Доступ к таблице допроса осуществляется через мастер-программу.

=== Таблица связей “Допрос персонажа”

|===
|Персонаж |Фокус             |Порог |Улика

|P1       |P2, L3, C4, С5, T2| 3.0  |C3
|P4       |C4, T5, T6        | 5.0  |C12
| *       |P5                | 5.2  |C15
|===

*Персонаж* - допрашиваемый персонаж.
Детектив на основе известных ему из хода расследования улик и логических заключений выбирает персонажа которого нужно
допросить.

*Фокус* - фокус допроса. То же что и <<search-focus, фокус обыска>>, но с дополнительным ограничением:
*Среди элементов фокуса обязательно должен быть как минимум один id сущности.*

*Порог*  - порог соправтивления психологическому давлению детектива.
_Действительное_ число, которое сравнивается с выпавшим на дайсе D12.
Если выпало меньше "Порога" - считается что детектив не смог преодалеть нежелание персонажа
делиться информацией и поэтому целевая улика не открывается.
В сценарии порог обнаружения задается таким образом, чтобы наиболее важные для следствия улики имели большие значения
порогов. Возможность указания дробных значений позволяет "тонко" упорядочить улики.

Для уменьшения влияния случайности, нужно указывать малые значения порогов, для исключения случанойсти - меньше 1

*Улика*  - целевая улика персонажа, который открывается при успешном допросе.
Улика может быть задана сценарием преднамеренно не верно - имитация того, что персонаж лжет/забыл.

=== Стоимость допроса, начисляемые очки

*Стоимость допроса* - ресурсная стоимость допроса любых персонажей одинакова и определяется в сценарии.
Определяет сколько тратится ресурса за допрос персонажа. Детектив узнает стоимость в начале игры.

*Очки за обыск* - базовое количество очков которые могут быть начислены детективу за допрос персонажа.
Для всех персонажей в сценарии определяется одинаковое базовое количество очков.
Базовые очки начисляются за открытие целевой улики при допросе (ложной или нет).
Начисляется по одному очку за каждое совпадение _сущности_ в фокусе (вне зависимости от открытия улики).

[[interrogation-alg]]
=== Алгоритм определения целевой улики в таблице допроса персонажа

Алгоритм определения целевой улики преследует следующую цель:
определить улику персонажа максимально соответствующую фокусу детектива, но при этом улики должны раскрываться начиная
с наименее значимой для расследования.

В алгоритме рассматриваются строки таблицы допроса, относящиеся к выбранному персонажу.
Из рассмотрения исключаются строки, для которых улика уже была открыта в предыдущих допросах.

1) Для каждой строки вычисляются веса фокуса A,B,N.  См. <<focus-weights-comp, вычисление весов соответствия фокусов>>

2) Находится строка с максимальным "A", максимальным "B", минимальным "N" и минимальным *Порогом*.

3) Если для этой строки "A = 0" - персонаж не знает о чем справшивает детектив. Целевая улика не открывается.
Сообщается о том что у персонажа нет нужной информации:

* Не совпавшие id сущностей и типы из фокуса детектива.
* Типы сущностей не совпавших id в табличном фокусе  (как намек на другие связи).

Например для фокуса детектива "L3,P?,T?" и табличного фокуса "L4, T1, C2" будет выведено:
"Персонаж P1 не знает о L3, P? но намекает, что знает о L?, T?, C?".

4) Если "A > 0" -  персонаж знает о чем справшивает детектив.

Для сообщения выбираются:

* Совпавшие id сущностей и типы в фокусе детектива.
* Типы сущностей не совпавших id в табличном фокусе.

4.1) Если "D12 >= Порог" - открывается целевая улика. Сообщается об открытии улики и связях:

Например для целевой улики C8 для фокуса детектива "L3, P?, C?" и табличного фокуса "L3, P7, P4, T2" будет выведено:
"Персонаж P1 знает о L3, P?, P?, T? связанных с C8".

Строка соответствующая целевой улике исключается из дальнейших допросов.
Если все улики персонажа открыты, на карту персонажа выкладывается жетон “Все улики обнаружены”.

4.2) Если "D12 < Порог" - целевая улика не открываетя. Сообщается лишь о связях:
"Персонаж P1 знает о L3, P?, P?, T?. Надавите на персонажа сильнее (+N)"

N - разница между D12 и порогом.

5) Сообщается сколько очков начислено детективу.

== Лабораторная экспертиза

В случае необходимости подтверждения гипотезы детективы могут заказать проведение лабораторной экспертизы для проверки
существования связи между *открытми* сущностями, у которых возможно нет прямых отсылок друг на друга.
Например определить, соответствует ли пепел найденный в локации сигаретам найденным у персонажа.

На проведение экспертизы влияют множество  случайных факторов которые опередяют ее результат.
Это влияние моделируется броском D12.

Экспертиза стоит определенного ресурса. За экспертизу детективу могут быть начислены очки.

Сценарий задает таблицу связей *“Лабораторная экспертиза”* которая определяет связь между сущностями.

Процедура проведения экспертизы:

. Детектив указывает фокус экспертизы - набор id любых *открытых* сущностей или любых типов, напрмимер C1, P?
. Бросает дайс D12 для моделирования влияния случайных факторов.
. По таблице “Экспертиза сущностей” определяется результат экспертизы.
Эта таблица доступна только через мастер-программу.
. По завершению экспертизы заполняется карточка “Экспертное заключение” в которой указываются результаты экспертизы.

=== Таблица связей “Лабораторная экспертиза”

|===
|Фокус          |Порог|Улика
| P2, L3, L5, T6|10.0 | C2
| P3, С3, С4    |7.1  | С4
|===

*Фокус* - фокус экспертизы. То же что и <<search-focus, фокус обыска>>, но с дополнительным ограничением:
*Среди элементов фокуса обязательно должен быть как минимум две id сущности.*

*Порог* - порог влияния случайных факторов на экспертизу.
_Действительное_ число, которое сравнивается с выпавшим на дайсе D12.
Если выпало меньше числа "Порога" - считается что негативное влияние факторов существенное,
экспертиза проведена не качественно и целевая улика не открывается.
В сценарии порог влияния задается таким образом, чтобы наиболее важные для следствия улики имели большие значения
порогов. Возможность указания дробных значений позволяет "тонко" упорядочить улики.

Для уменьшения влияния случайности, нужно указывать малые значения порогов, для исключения случанойсти - меньше 1

*Улика* - целевая улика, по сути - лабораторное заключение, детализирующее связь.
Например "Обнаруженные отпечатки пальцев совпадают".

=== Стоимость экспертизы, начисляемые очки

*Стоимость экспертизы* - ресурсная стоимость любой экспертизы одинакова и определяется в сценарии.
Определяет сколько тратится ресурса за проведение экспертизы. Детектив узнает стоимость в начале игры.

*Очки за экспертизу* - базовое количество очков которые могут быть начислены детективу за экспертизу.
Для всех экспертиз в сценарии определяется одинаковое базовое количество очков.
Базовые очки начисляются детективу за открытие улики.
Начисляется по одному очку за каждое совпадение _сущности_ в фокусе (вне зависимости от открытия улики).

== Алгоритм выявления строки связи в таблице экспертиза

Алгоритм определения связи преследует следующую цель:
определить наличие связи и дополнительных данных для сущностей, максимально соответствующих фокусу детектива и броску
D12.

Из рассмотрения исключаются строки, для которых в предыдущих экспертизах была открыта целевая улика.

[[expertise-quality]]
1) Для каждой строки вычисляются веса фокуса A,B,N.  См. <<focus-weights-comp, вычисление весов соответствия фокусов>>

2) Находится строка с максимальным "A", максимальным "B", минимальным "N", мнимальным "Порогом"

3) Если "A = 0" - связи не выявлены. Целевая улика не открывается.
Сообщается о не выявлении связи:

* Не совпавшие id сущностей и типы из фокуса детектива.
* Типы сущностей не совпавших id в табличном фокусе  (как рекомендуемые).

Например: "Связь между L2, P4, C? не выявлена. Рекомендуется экспертиза L?, P?, T?"

4) Если "A = 1" - выявлены связи для одной сущности. Целевая улика не открывается.
Сообщается о связях "в общем":

* Совпавшие id сущностей в фокусе детектива.
* Типы сущностей в табличном фокусе, кроме совпавших с id из фокуса детектива

Например для фокус детектива "L2,L3,P?"  и табличного  "L2,L4,P1,T3":
"Выявлена связь L2 c L?, P?, T?"

5) Если "A > 1" - связь обнаружена.

Целевая улика открывается.
Сообщение об обнаружении связи и открытии улики (заключении экспертизы):

* Совпавшие id сущностей в фокусе детектива.
* Типы сущностей в табличном фокусе, кроме совпавших с id из фокуса детектива

Например: "Обнаружена связь L2,P4 с L?,T?,P?. Заключение экспертизы С3"

Строка с открытой уликой исключается из дальнейших экспертиз.
Если для всех строк таблицы экспертизы целевые улики открыты, выкладывается жетон “Лаборатория закрыта”.

6) Сообщается сколько очков начислено детективу.

[[focus-stat-hint]]
== Статистики фокуса

Получение статистики фокусов является опциональной механикой, возможность использования
регулируется в сценарии. Получение статистики может быть разрешено для уменьшения сложности
игры для новичков.

Получение статистики фокуса может быть как бесплатным так и стоить определенного ресурса (обозначается в сценарии)

[[location-glue-hint]]
=== Статистика локации

Перед проведением обыска детектив может запросить
статистику локации:

. Вычисляется процент каждого из типов сущностей во всех фокусах локации.
. Выдается статистика: "Возможные связи локации с P 45%, L 30%, T 25%, C 0%"

[[personage-glue-hint]]
=== Статистика персонажа

Перед проведением допроса детектив может запросить
статистику персонажа:

. Вычисляется процент каждого из типов сущностей во всех фокусах персонажа.
. Выдается статистика: "Персонаж может знать о P 45%, L 30%, T 25%, C 0%"

[[expertise-glue-hint]]
=== Статистика лаборатории

Перед проведением экспертизы детектив может запросить
статистику лаборатории:

. Вычисляется процент каждого из типов сущностей во всех табличных фокусах экспертизы.
. Выдается статистика: "Лаборатория может определить связи между P 45%, L 30%, T 25%, C 0%"

== Прямые связи сущностей

Прямая связь между любыми сущностями возможна через упоминание в улики а также в таблице Экспертиза сущностей.
Также связи затаюся согласно таблице:

|===
| |Локация |Время |Улика |Персонаж

|Локация |Переходы между локациями| |Обнаружение улики в локации|
|Время | |Соседние такты||
|Улика | | || Обнаружение улики у персонажа
|Персонаж | | | |
|===

== Шаблон сценария

<<script-template-ru.adoc, См. файл script-template.adoc>>

== Руководство по созданию сценария

<<script-guide-ru.adoc, См. файл script-guide-ru.adoc>>